# Generated by Django 5.2.17 on 2026-09-03 15:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('type_tiers', models.CharField(choices=[('PERSONNE', 'Personne physique'), ('ENTREPRISE', 'Personne morale')], default='ENTREPRISE', max_length=20, verbose_name='type de tiers')),
                ('raison_sociale', models.CharField(max_length=200, verbose_name='raison sociale')),
                ('rccm', models.CharField(blank=True, max_length=50, verbose_name='RCCM')),
                ('nif', models.CharField(blank=True, max_length=50, verbose_name='NIF')),
                ('telephone', models.CharField(max_length=20, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('note_evaluation', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name="note d'évaluation")),
                ('est_actif', models.BooleanField(default=True, verbose_name='est actif')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'tiers',
                'verbose_name_plural': 'tiers',
                'db_table': 'tiers',
                'ordering': ['raison_sociale'],
            },
        ),
        migrations.CreateModel(
            name='RoleTiers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('role', models.CharField(choices=[('CLIENT_MOA', "Client / Maître d'ouvrage"), ('FOURNISSEUR', 'Fournisseur'), ('SOUS_TRAITANT', 'Sous-traitant'), ('TACHERON', 'Tâcheron'), ('BUREAU_CONTROLE', 'Bureau de contrôle'), ('ADMINISTRATION', 'Administration'), ('PRESTATAIRE', 'Prestataire')], max_length=30, verbose_name='rôle')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('tiers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tiers.tiers')),
            ],
            options={
                'verbose_name': 'rôle de tiers',
                'verbose_name_plural': 'rôles de tiers',
                'db_table': 'role_tiers',
                'constraints': [models.UniqueConstraint(fields=('tiers', 'role'), name='uq_role_tiers')],
            },
        ),
    ]
