# Generated by Django 5.2.17 on 2026-10-02 11:01

import django.db.migrations.operations.special
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


def reporter_les_blocages(apps, schema_editor):
    from django.utils import timezone
    Utilisateur = apps.get_model("accounts", "Utilisateur")
    maintenant = timezone.now()
    Utilisateur.objects.filter(bloque_jusqu_a__gt=maintenant).update(bloque_le=maintenant)

def rendre_les_echeances(apps, schema_editor):
    from datetime import timedelta
    from django.utils import timezone
    Utilisateur = apps.get_model("accounts", "Utilisateur")
    Utilisateur.objects.filter(bloque_le__isnull=False).update(
        bloque_jusqu_a=timezone.now() + timedelta(minutes=15)
    )

def restreindre_est_systeme(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    Role.objects.exclude(code__in={"DG", "AD"}).update(est_systeme=False)

def annuler_restriction(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    Role.objects.filter(code__in={"DG", "AD", "CP", "CT", "CC", "MOA", "MOE", "VI"}).update(est_systeme=True)

def purger_modules_obsoletes(apps, schema_editor):
    RoleModulePermission = apps.get_model("accounts", "RoleModulePermission")
    RoleModulePermission.objects.filter(
        module__in={"finance", "achats", "stocks", "rh", "equipements", "qhse", "contrats"},
    ).delete()

def restaurer_modules_obsoletes(apps, schema_editor):
    pass

MODULES_INITIAUX = [
    {
        "code": "projets",
        "libelle": "Gestion des Projets",
        "description": "Fiches projets, lots, activités, jalons et planification des chantiers.",
        "ordre": 1,
        "icone": "folder-kanban",
        "est_actif": True,
    },
    {
        "code": "chantier",
        "libelle": "Suivi Technique / Chantier",
        "description": "Rapports journaliers, avancement des travaux, blocages terrain et pointages.",
        "ordre": 2,
        "icone": "hard-hat",
        "est_actif": True,
    },
    {
        "code": "ged",
        "libelle": "Gestion Documentaire (GED)",
        "description": "Classeurs, plans d'exécution, procès-verbaux et traçabilité des pièces jointes.",
        "ordre": 3,
        "icone": "file-text",
        "est_actif": True,
    },
    {
        "code": "pilotage",
        "libelle": "Tableaux de bord & Pilotage",
        "description": "Indicateurs d'avancement, indice de santé global, météo et aide à la décision.",
        "ordre": 4,
        "icone": "bar-chart-3",
        "est_actif": True,
    },
    {
        "code": "tiers",
        "libelle": "Parties Prenantes / Tiers",
        "description": "Clients, maîtres d'ouvrage, sous-traitants, fournisseurs et partenaires.",
        "ordre": 5,
        "icone": "users",
        "est_actif": True,
    },
]

def seed_modules(apps, schema_editor):
    Module = apps.get_model("accounts", "Module")
    for data in MODULES_INITIAUX:
        Module.objects.update_or_create(code=data["code"], defaults=data)

def unseed_modules(apps, schema_editor):
    Module = apps.get_model("accounts", "Module")
    codes = [d["code"] for d in MODULES_INITIAUX]
    Module.objects.filter(code__in=codes).delete()

def migrer_vers_fk(apps, schema_editor):
    RoleModulePermission = apps.get_model("accounts", "RoleModulePermission")
    Module = apps.get_model("accounts", "Module")
    modules_map = {m.code: m for m in Module.objects.all()}
    for perm in RoleModulePermission.objects.all():
        mod = modules_map.get(perm.module)
        if mod:
            perm.module_fk = mod
            perm.save(update_fields=["module_fk"])
        else:
            perm.delete()

def migrer_vers_charfield(apps, schema_editor):
    RoleModulePermission = apps.get_model("accounts", "RoleModulePermission")
    for perm in RoleModulePermission.objects.all():
        if perm.module_fk_id:
            Module = apps.get_model("accounts", "Module")
            mod = Module.objects.filter(id=perm.module_fk_id).first()
            if mod:
                perm.module = mod.code
                perm.save(update_fields=["module"])

PERMISSIONS_INITIALES = [
    {
        "code": "LECTURE",
        "libelle": "Lecture / Consultation",
        "description": "Permet de consulter et visualiser les données du module.",
        "ordre": 1,
        "est_actif": True,
    },
    {
        "code": "ECRITURE",
        "libelle": "Écriture / Saisie",
        "description": "Permet de créer, éditer et modifier les données du module.",
        "ordre": 2,
        "est_actif": True,
    },
    {
        "code": "VALIDATION",
        "libelle": "Validation / Approbation",
        "description": "Permet de valider, approuver, signer ou rejeter les éléments du module.",
        "ordre": 3,
        "est_actif": True,
    },
    {
        "code": "SUPPRESSION",
        "libelle": "Suppression / Archivage",
        "description": "Permet de supprimer ou archiver les éléments du module.",
        "ordre": 4,
        "est_actif": True,
    },
]

def seed_permissions_and_migrate_roles(apps, schema_editor):
    Permission = apps.get_model("accounts", "Permission")
    RoleModulePermission = apps.get_model("accounts", "RoleModulePermission")
    perms_map = {}
    for data in PERMISSIONS_INITIALES:
        p, _ = Permission.objects.update_or_create(code=data["code"], defaults=data)
        perms_map[data["code"]] = p

    for rmp in RoleModulePermission.objects.all():
        niveau = rmp.niveau
        to_add = []
        if niveau == 1:
            if "LECTURE" in perms_map:
                to_add.append(perms_map["LECTURE"])
        elif niveau == 2:
            for c in ["LECTURE", "ECRITURE"]:
                if c in perms_map:
                    to_add.append(perms_map[c])
        elif niveau is not None and niveau >= 3:
            for c in ["LECTURE", "ECRITURE", "VALIDATION"]:
                if c in perms_map:
                    to_add.append(perms_map[c])
        if to_add:
            rmp.permissions.add(*to_add)

def rendre_admin_supprimable(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    Role.objects.filter(code="AD").update(est_systeme=False)

def annuler_suppression(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    Role.objects.filter(code="AD").update(est_systeme=True)

def seed_permission_modules_m2m(apps, schema_editor):
    Permission = apps.get_model("accounts", "Permission")
    Module = apps.get_model("accounts", "Module")
    modules_actifs = list(Module.objects.filter(est_actif=True, supprime_le__isnull=True))
    if not modules_actifs:
        return
    for perm in Permission.objects.filter(est_actif=True, supprime_le__isnull=True):
        perm.modules.add(*modules_actifs)

def unseed_permission_modules_m2m(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    replaces = [('accounts', '0001_initial'), ('accounts', '0002_utilisateur_doit_changer_mot_de_passe'), ('accounts', '0003_jetonreinitialisation'), ('accounts', '0004_invitation_mld_conformite'), ('accounts', '0005_role_utilisateur_role_personnalise_and_more'), ('accounts', '0006_utilisateur_is_owner'), ('accounts', '0007_alter_invitation_role_propose_and_more'), ('accounts', '0008_blocage_sans_echeance'), ('accounts', '0009_utilisateur_avatar'), ('accounts', '0010_alter_invitation_role_propose_and_more'), ('accounts', '0011_restreindre_est_systeme_dg_admin'), ('accounts', '0012_purger_modules_obsoletes'), ('accounts', '0013_create_module_and_seed'), ('accounts', '0014_rolemodulepermission_module_fk'), ('accounts', '0015_alter_rolemodulepermission_niveau_permission_and_more'), ('accounts', '0016_permission_modules_m2m'), ('accounts', '0017_rendre_role_admin_supprimable_par_dg'), ('accounts', '0018_seed_permission_modules_m2m')]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='prénom')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('role_global', models.CharField(choices=[('AD', 'Administrateur'), ('DG', 'Directeur Général'), ('DF', 'Directeur Financier'), ('CP', 'Chef de Projet'), ('CT', 'Conducteur de Travaux'), ('CC', 'Chef de Chantier'), ('VI', 'Visiteur')], db_index=True, default='VI', max_length=5, verbose_name='rôle global')),
                ('statut', models.CharField(choices=[('INVITE', 'Invité'), ('ACTIF', 'Actif'), ('DESACTIVE', 'Désactivé')], db_index=True, default='INVITE', max_length=20, verbose_name='statut')),
                ('tentatives_echouees', models.PositiveSmallIntegerField(default=0, verbose_name='tentatives échouées')),
                ('bloque_jusqu_a', models.DateTimeField(blank=True, null=True, verbose_name="bloqué jusqu'à")),
                ('double_authentification', models.BooleanField(default=False, verbose_name='double authentification')),
                ('langue', models.CharField(default='fr', max_length=5, verbose_name='langue')),
                ('is_staff', models.BooleanField(default=False, verbose_name="accès à l'administration")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'db_table': 'utilisateur',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Appareil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('type_appareil', models.CharField(choices=[('WEB', 'Navigateur web'), ('ANDROID', 'Android'), ('IOS', 'iOS')], max_length=20, verbose_name='type')),
                ('jeton_push', models.CharField(blank=True, max_length=255, verbose_name='jeton push FCM')),
                ('identifiant_materiel', models.CharField(blank=True, max_length=100, verbose_name='identifiant matériel')),
                ('derniere_activite', models.DateTimeField(blank=True, null=True, verbose_name='dernière activité')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='appareils', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'appareil',
                'verbose_name_plural': 'appareils',
                'db_table': 'appareil',
                'ordering': ['-derniere_activite'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('role_propose', models.CharField(choices=[('AD', 'Administrateur'), ('DG', 'Directeur Général'), ('DF', 'Directeur Financier'), ('CP', 'Chef de Projet'), ('CT', 'Conducteur de Travaux'), ('CC', 'Chef de Chantier'), ('VI', 'Visiteur')], max_length=5, verbose_name='rôle proposé')),
                ('jeton', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='jeton')),
                ('expire_le', models.DateTimeField(verbose_name='expire le')),
                ('statut', models.CharField(choices=[('ENVOYEE', 'Envoyée'), ('ACCEPTEE', 'Acceptée'), ('EXPIREE', 'Expirée'), ('REVOQUEE', 'Révoquée')], default='ENVOYEE', max_length=20, verbose_name='statut')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'invitation',
                'verbose_name_plural': 'invitations',
                'db_table': 'invitation',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddConstraint(
            model_name='utilisateur',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('supprime_le__isnull', True)), name='uq_utilisateur_email'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='doit_changer_mot_de_passe',
            field=models.BooleanField(default=False, verbose_name='doit changer son mot de passe'),
        ),
        migrations.CreateModel(
            name='JetonReinitialisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('empreinte', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='empreinte')),
                ('motif', models.CharField(choices=[('OUBLI', 'Mot de passe oublié'), ('BLOCAGE', 'Compte bloqué')], max_length=20, verbose_name='motif')),
                ('expire_le', models.DateTimeField(verbose_name='expire le')),
                ('utilise_le', models.DateTimeField(blank=True, null=True, verbose_name='utilisé le')),
                ('invalide_le', models.DateTimeField(blank=True, null=True, verbose_name='invalidé le')),
                ('ip_demande', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de la demande')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='jetons_reinitialisation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'jeton de réinitialisation',
                'verbose_name_plural': 'jetons de réinitialisation',
                'db_table': 'jeton_reinitialisation',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='jeton',
        ),
        migrations.AddField(
            model_name='invitation',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='empreinte',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='empreinte'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='emetteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='invitations_emises', to=settings.AUTH_USER_MODEL, verbose_name='émetteur'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='utilise_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='utilisé le'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='code')),
                ('libelle', models.CharField(max_length=100, verbose_name='libellé')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('est_systeme', models.BooleanField(default=False, help_text='Un rôle système ne peut pas être supprimé.', verbose_name='est un rôle système')),
                ('est_actif', models.BooleanField(default=True, verbose_name='est actif')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'rôle',
                'verbose_name_plural': 'rôles',
                'db_table': 'role',
                'ordering': ['libelle'],
            },
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='role_personnalise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='accounts.role', verbose_name='rôle personnalisé'),
        ),
        migrations.CreateModel(
            name='RoleModulePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('module', models.CharField(choices=[('projets', 'Gestion des Projets'), ('chantier', 'Suivi Technique / Chantier'), ('finance', 'Gestion Financière'), ('achats', 'Achats & Approvisionnements'), ('stocks', 'Gestion des Stocks'), ('rh', 'Ressources Humaines'), ('equipements', 'Matériel & Équipements'), ('qhse', 'QHSE'), ('contrats', 'Contrats & Sous-traitance'), ('tiers', 'Parties Prenantes / Tiers'), ('ged', 'Gestion Documentaire (GED)'), ('pilotage', 'Pilotage & Tableaux de bord')], max_length=30, verbose_name='module')),
                ('niveau', models.PositiveSmallIntegerField(choices=[(0, 'Aucun'), (1, 'Lecture'), (2, 'Écriture / Saisie'), (3, 'Validation / Approbation')], default=0, verbose_name="niveau d'accès")),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_modules', to='accounts.role', verbose_name='rôle')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'permission module du rôle',
                'verbose_name_plural': 'permissions modules du rôle',
                'db_table': 'role_module_permission',
            },
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('supprime_le__isnull', True)), fields=('code',), name='uq_role_code_actif'),
        ),
        migrations.AddConstraint(
            model_name='rolemodulepermission',
            constraint=models.UniqueConstraint(condition=models.Q(('supprime_le__isnull', True)), fields=('role', 'module'), name='uq_role_module_actif'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='propriétaire / fondateur'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role_propose',
            field=models.CharField(choices=[('AD', 'Administrateur'), ('DG', 'Directeur Général / PDG'), ('CP', 'Chef de Projet'), ('CT', 'Conducteur de Travaux'), ('CC', 'Chef de Chantier'), ('MOA', "Maître d'Ouvrage (Client)"), ('VI', 'Visiteur')], max_length=5, verbose_name='rôle proposé'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role_global',
            field=models.CharField(choices=[('AD', 'Administrateur'), ('DG', 'Directeur Général / PDG'), ('CP', 'Chef de Projet'), ('CT', 'Conducteur de Travaux'), ('CC', 'Chef de Chantier'), ('MOA', "Maître d'Ouvrage (Client)"), ('VI', 'Visiteur')], db_index=True, default='VI', max_length=5, verbose_name='rôle global'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='bloque_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='bloqué le'),
        ),
        migrations.RunPython(
            code=reporter_les_blocages,
            reverse_code=rendre_les_echeances,
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='bloque_jusqu_a',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='avatar',
            field=models.ImageField(blank=True, help_text="Photo de profil de l'utilisateur (format image, max 2 Mo).", null=True, upload_to='avatars/%Y/%m/', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role_propose',
            field=models.CharField(choices=[('AD', 'Administrateur'), ('DG', 'Directeur Général / PDG'), ('CP', 'Chef de Projet'), ('CT', 'Conducteur de Travaux'), ('CC', 'Chef de Chantier'), ('MOA', "Maître d'Ouvrage (Client)"), ('MOE', "Maître d'Œuvre"), ('VI', 'Consultant lecture')], max_length=5, verbose_name='rôle proposé'),
        ),
        migrations.AlterField(
            model_name='rolemodulepermission',
            name='module',
            field=models.CharField(choices=[('projets', 'Gestion des Projets'), ('chantier', 'Suivi Technique / Chantier'), ('ged', 'Gestion Documentaire (GED)'), ('pilotage', 'Tableaux de bord & Pilotage'), ('tiers', 'Parties Prenantes / Tiers')], max_length=30, verbose_name='module'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role_global',
            field=models.CharField(choices=[('AD', 'Administrateur'), ('DG', 'Directeur Général / PDG'), ('CP', 'Chef de Projet'), ('CT', 'Conducteur de Travaux'), ('CC', 'Chef de Chantier'), ('MOA', "Maître d'Ouvrage (Client)"), ('MOE', "Maître d'Œuvre"), ('VI', 'Consultant lecture')], db_index=True, default='VI', max_length=5, verbose_name='rôle global'),
        ),
        migrations.RunPython(
            code=restreindre_est_systeme,
            reverse_code=annuler_restriction,
        ),
        migrations.RunPython(
            code=purger_modules_obsoletes,
            reverse_code=restaurer_modules_obsoletes,
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('code', models.CharField(db_index=True, help_text="Code technique unique du module (ex: 'projets', 'chantier', 'ged').", max_length=30, verbose_name='code')),
                ('libelle', models.CharField(help_text='Nom officiel et lisible du module.', max_length=100, verbose_name='libellé')),
                ('description', models.TextField(blank=True, default='', help_text='Périmètre fonctionnel et fonctionnalités couvertes par ce module.', verbose_name='description')),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text='Position ordonnée dans la navigation et les matrices de permissions.', verbose_name="ordre d'affichage")),
                ('icone', models.CharField(blank=True, default='box', help_text="Identifiant de l'icône Lucide / frontend associée.", max_length=50, verbose_name='icône')),
                ('est_actif', models.BooleanField(default=True, help_text='Indique si le module est disponible dans ce tenant.', verbose_name='est actif')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
                'db_table': 'module',
                'ordering': ['ordre', 'code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('supprime_le__isnull', True)), fields=('code',), name='uq_module_code_actif')],
            },
        ),
        migrations.RunPython(
            code=seed_modules,
            reverse_code=unseed_modules,
        ),
        migrations.AddField(
            model_name='rolemodulepermission',
            name='module_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions_roles', to='accounts.module', verbose_name='module'),
        ),
        migrations.RunPython(
            code=migrer_vers_fk,
            reverse_code=migrer_vers_charfield,
        ),
        migrations.RemoveConstraint(
            model_name='rolemodulepermission',
            name='uq_role_module_actif',
        ),
        migrations.RemoveField(
            model_name='rolemodulepermission',
            name='module',
        ),
        migrations.RenameField(
            model_name='rolemodulepermission',
            old_name='module_fk',
            new_name='module',
        ),
        migrations.AlterField(
            model_name='rolemodulepermission',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_roles', to='accounts.module', verbose_name='module'),
        ),
        migrations.AddConstraint(
            model_name='rolemodulepermission',
            constraint=models.UniqueConstraint(condition=models.Q(('supprime_le__isnull', True)), fields=('role', 'module'), name='uq_role_module_actif'),
        ),
        migrations.AlterField(
            model_name='rolemodulepermission',
            name='niveau',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Aucun'), (1, 'Lecture'), (2, 'Écriture / Saisie'), (3, 'Validation / Approbation')], default=0, null=True, verbose_name="niveau d'accès"),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('code', models.CharField(db_index=True, help_text="Code technique unique de l'autorisation (ex: 'LECTURE', 'ECRITURE', 'VALIDATION').", max_length=50, verbose_name='code')),
                ('libelle', models.CharField(help_text="Nom officiel et lisible de l'autorisation.", max_length=100, verbose_name='libellé')),
                ('description', models.TextField(blank=True, default='', help_text="Description de l'action ou capacité conférée par cette permission.", verbose_name='description')),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text='Position ordonnée dans les grilles et formulaires de permissions.', verbose_name="ordre d'affichage")),
                ('est_actif', models.BooleanField(default=True, help_text='Indique si cette permission est active et disponible.', verbose_name='est actif')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
                'db_table': 'permission',
                'ordering': ['ordre', 'code'],
            },
        ),
        migrations.AddField(
            model_name='rolemodulepermission',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles_modules', to='accounts.permission', verbose_name='permissions accordées'),
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(condition=models.Q(('supprime_le__isnull', True)), fields=('code',), name='uq_permission_code_actif'),
        ),
        migrations.RunPython(
            code=seed_permissions_and_migrate_roles,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='permission',
            name='modules',
            field=models.ManyToManyField(blank=True, help_text='Modules fonctionnels et applicatifs autorisés à porter cette permission.', related_name='permissions', to='accounts.module', verbose_name='modules éligibles'),
        ),
        migrations.RunPython(
            code=rendre_admin_supprimable,
            reverse_code=annuler_suppression,
        ),
        migrations.RunPython(
            code=seed_permission_modules_m2m,
            reverse_code=unseed_permission_modules_m2m,
        ),
    ]
