# Generated by Django 5.2.17 on 2026-08-24 16:06

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='prénom')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('role_global', models.CharField(choices=[('AD', 'Administrateur'), ('DG', 'Directeur Général'), ('DF', 'Directeur Financier'), ('CP', 'Chef de Projet'), ('CT', 'Conducteur de Travaux'), ('CC', 'Chef de Chantier'), ('VI', 'Visiteur')], db_index=True, default='VI', max_length=5, verbose_name='rôle global')),
                ('statut', models.CharField(choices=[('INVITE', 'Invité'), ('ACTIF', 'Actif'), ('DESACTIVE', 'Désactivé')], db_index=True, default='INVITE', max_length=20, verbose_name='statut')),
                ('tentatives_echouees', models.PositiveSmallIntegerField(default=0, verbose_name='tentatives échouées')),
                ('bloque_jusqu_a', models.DateTimeField(blank=True, null=True, verbose_name="bloqué jusqu'à")),
                ('double_authentification', models.BooleanField(default=False, verbose_name='double authentification')),
                ('langue', models.CharField(default='fr', max_length=5, verbose_name='langue')),
                ('is_staff', models.BooleanField(default=False, verbose_name="accès à l'administration")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'db_table': 'utilisateur',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Appareil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('type_appareil', models.CharField(choices=[('WEB', 'Navigateur web'), ('ANDROID', 'Android'), ('IOS', 'iOS')], max_length=20, verbose_name='type')),
                ('jeton_push', models.CharField(blank=True, max_length=255, verbose_name='jeton push FCM')),
                ('identifiant_materiel', models.CharField(blank=True, max_length=100, verbose_name='identifiant matériel')),
                ('derniere_activite', models.DateTimeField(blank=True, null=True, verbose_name='dernière activité')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='appareils', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'appareil',
                'verbose_name_plural': 'appareils',
                'db_table': 'appareil',
                'ordering': ['-derniere_activite'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('role_propose', models.CharField(choices=[('AD', 'Administrateur'), ('DG', 'Directeur Général'), ('DF', 'Directeur Financier'), ('CP', 'Chef de Projet'), ('CT', 'Conducteur de Travaux'), ('CC', 'Chef de Chantier'), ('VI', 'Visiteur')], max_length=5, verbose_name='rôle proposé')),
                ('jeton', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='jeton')),
                ('expire_le', models.DateTimeField(verbose_name='expire le')),
                ('statut', models.CharField(choices=[('ENVOYEE', 'Envoyée'), ('ACCEPTEE', 'Acceptée'), ('EXPIREE', 'Expirée'), ('REVOQUEE', 'Révoquée')], default='ENVOYEE', max_length=20, verbose_name='statut')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'invitation',
                'verbose_name_plural': 'invitations',
                'db_table': 'invitation',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddConstraint(
            model_name='utilisateur',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('supprime_le__isnull', True)), name='uq_utilisateur_email'),
        ),
    ]
