# Generated by Django 5.2.17 on 2026-09-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='doit_changer_mot_de_passe',
            field=models.BooleanField(default=False, verbose_name='doit changer son mot de passe'),
        ),
    ]
