# Generated by Django 5.2.17 on 2026-09-02 16:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_utilisateur_doit_changer_mot_de_passe'),
    ]

    operations = [
        migrations.CreateModel(
            name='JetonReinitialisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('empreinte', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='empreinte')),
                ('motif', models.CharField(choices=[('OUBLI', 'Mot de passe oublié'), ('BLOCAGE', 'Compte bloqué')], max_length=20, verbose_name='motif')),
                ('expire_le', models.DateTimeField(verbose_name='expire le')),
                ('utilise_le', models.DateTimeField(blank=True, null=True, verbose_name='utilisé le')),
                ('invalide_le', models.DateTimeField(blank=True, null=True, verbose_name='invalidé le')),
                ('ip_demande', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de la demande')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='jetons_reinitialisation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'jeton de réinitialisation',
                'verbose_name_plural': 'jetons de réinitialisation',
                'db_table': 'jeton_reinitialisation',
                'ordering': ['-cree_le'],
            },
        ),
    ]
