# Generated by Django 5.2.17 on 2026-09-04 14:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_invitation_mld_conformite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='code')),
                ('libelle', models.CharField(max_length=100, verbose_name='libellé')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('est_systeme', models.BooleanField(default=False, help_text='Un rôle système ne peut pas être supprimé.', verbose_name='est un rôle système')),
                ('est_actif', models.BooleanField(default=True, verbose_name='est actif')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'rôle',
                'verbose_name_plural': 'rôles',
                'db_table': 'role',
                'ordering': ['libelle'],
            },
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='role_personnalise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='accounts.role', verbose_name='rôle personnalisé'),
        ),
        migrations.CreateModel(
            name='RoleModulePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('module', models.CharField(choices=[('projets', 'Gestion des Projets'), ('chantier', 'Suivi Technique / Chantier'), ('finance', 'Gestion Financière'), ('achats', 'Achats & Approvisionnements'), ('stocks', 'Gestion des Stocks'), ('rh', 'Ressources Humaines'), ('equipements', 'Matériel & Équipements'), ('qhse', 'QHSE'), ('contrats', 'Contrats & Sous-traitance'), ('tiers', 'Parties Prenantes / Tiers'), ('ged', 'Gestion Documentaire (GED)'), ('pilotage', 'Pilotage & Tableaux de bord')], max_length=30, verbose_name='module')),
                ('niveau', models.PositiveSmallIntegerField(choices=[(0, 'Aucun'), (1, 'Lecture'), (2, 'Écriture / Saisie'), (3, 'Validation / Approbation')], default=0, verbose_name="niveau d'accès")),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_modules', to='accounts.role', verbose_name='rôle')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'permission module du rôle',
                'verbose_name_plural': 'permissions modules du rôle',
                'db_table': 'role_module_permission',
            },
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('supprime_le__isnull', True)), fields=('code',), name='uq_role_code_actif'),
        ),
        migrations.AddConstraint(
            model_name='rolemodulepermission',
            constraint=models.UniqueConstraint(condition=models.Q(('supprime_le__isnull', True)), fields=('role', 'module'), name='uq_role_module_actif'),
        ),
    ]
