# Generated by Django 5.2.17 on 2026-09-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_role_utilisateur_role_personnalise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='propriétaire / fondateur'),
        ),
    ]
