# Generated by Django 5.2.17 on 2026-09-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_utilisateur_is_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role_propose',
            field=models.CharField(choices=[('AD', 'Administrateur'), ('DG', 'Directeur Général / PDG'), ('DP', 'Directeur de Projet'), ('CP', 'Chef de Projet'), ('CT', 'Conducteur de Travaux'), ('CC', 'Chef de Chantier'), ('IT', 'Ingénieur / Technicien'), ('RF', 'Responsable Financier'), ('DF', 'Directeur Financier'), ('RA', 'Responsable Achats'), ('MAG', 'Magasinier'), ('RH', 'Responsable RH'), ('ST', 'Sous-traitant'), ('FRN', 'Fournisseur'), ('MOA', "Maître d'Ouvrage (Client)"), ('VI', 'Visiteur')], max_length=5, verbose_name='rôle proposé'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role_global',
            field=models.CharField(choices=[('AD', 'Administrateur'), ('DG', 'Directeur Général / PDG'), ('DP', 'Directeur de Projet'), ('CP', 'Chef de Projet'), ('CT', 'Conducteur de Travaux'), ('CC', 'Chef de Chantier'), ('IT', 'Ingénieur / Technicien'), ('RF', 'Responsable Financier'), ('DF', 'Directeur Financier'), ('RA', 'Responsable Achats'), ('MAG', 'Magasinier'), ('RH', 'Responsable RH'), ('ST', 'Sous-traitant'), ('FRN', 'Fournisseur'), ('MOA', "Maître d'Ouvrage (Client)"), ('VI', 'Visiteur')], db_index=True, default='VI', max_length=5, verbose_name='rôle global'),
        ),
    ]
