# Generated by Django 5.2.17 on 2026-09-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_blocage_sans_echeance'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='avatar',
            field=models.ImageField(blank=True, help_text="Photo de profil de l'utilisateur (format image, max 2 Mo).", null=True, upload_to='avatars/%Y/%m/', verbose_name='avatar'),
        ),
    ]
