# Generated by Django 5.2.17 on 2026-09-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_utilisateur_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role_propose',
            field=models.CharField(choices=[('AD', 'Administrateur'), ('DG', 'Directeur Général / PDG'), ('CP', 'Chef de Projet'), ('CT', 'Conducteur de Travaux'), ('CC', 'Chef de Chantier'), ('MOA', "Maître d'Ouvrage (Client)"), ('MOE', "Maître d'Œuvre"), ('VI', 'Consultant lecture')], max_length=5, verbose_name='rôle proposé'),
        ),
        migrations.AlterField(
            model_name='rolemodulepermission',
            name='module',
            field=models.CharField(choices=[('projets', 'Gestion des Projets'), ('chantier', 'Suivi Technique / Chantier'), ('ged', 'Gestion Documentaire (GED)'), ('pilotage', 'Tableaux de bord & Pilotage'), ('tiers', 'Parties Prenantes / Tiers')], max_length=30, verbose_name='module'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role_global',
            field=models.CharField(choices=[('AD', 'Administrateur'), ('DG', 'Directeur Général / PDG'), ('CP', 'Chef de Projet'), ('CT', 'Conducteur de Travaux'), ('CC', 'Chef de Chantier'), ('MOA', "Maître d'Ouvrage (Client)"), ('MOE', "Maître d'Œuvre"), ('VI', 'Consultant lecture')], db_index=True, default='VI', max_length=5, verbose_name='rôle global'),
        ),
    ]
