# Generated by Django 5.2.17 on 2026-09-30 11:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


PERMISSIONS_INITIALES = [
    {
        "code": "LECTURE",
        "libelle": "Lecture / Consultation",
        "description": "Permet de consulter et visualiser les données du module.",
        "ordre": 1,
        "est_actif": True,
    },
    {
        "code": "ECRITURE",
        "libelle": "Écriture / Saisie",
        "description": "Permet de créer, éditer et modifier les données du module.",
        "ordre": 2,
        "est_actif": True,
    },
    {
        "code": "VALIDATION",
        "libelle": "Validation / Approbation",
        "description": "Permet de valider, approuver, signer ou rejeter les éléments du module.",
        "ordre": 3,
        "est_actif": True,
    },
    {
        "code": "SUPPRESSION",
        "libelle": "Suppression / Archivage",
        "description": "Permet de supprimer ou archiver les éléments du module.",
        "ordre": 4,
        "est_actif": True,
    },
]


def seed_permissions_and_migrate_roles(apps, schema_editor):
    Permission = apps.get_model("accounts", "Permission")
    RoleModulePermission = apps.get_model("accounts", "RoleModulePermission")

    perms_map = {}
    for data in PERMISSIONS_INITIALES:
        p, _ = Permission.objects.update_or_create(code=data["code"], defaults=data)
        perms_map[data["code"]] = p

    # Migrer les permissions existantes depuis 'niveau'
    for rmp in RoleModulePermission.objects.all():
        niveau = rmp.niveau
        to_add = []
        if niveau == 1:
            if "LECTURE" in perms_map:
                to_add.append(perms_map["LECTURE"])
        elif niveau == 2:
            for c in ["LECTURE", "ECRITURE"]:
                if c in perms_map:
                    to_add.append(perms_map[c])
        elif niveau is not None and niveau >= 3:
            for c in ["LECTURE", "ECRITURE", "VALIDATION"]:
                if c in perms_map:
                    to_add.append(perms_map[c])
        if to_add:
            rmp.permissions.add(*to_add)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rolemodulepermission_module_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodulepermission',
            name='niveau',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Aucun'), (1, 'Lecture'), (2, 'Écriture / Saisie'), (3, 'Validation / Approbation')], default=0, null=True, verbose_name="niveau d'accès"),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('code', models.CharField(db_index=True, help_text="Code technique unique de l'autorisation (ex: 'LECTURE', 'ECRITURE', 'VALIDATION').", max_length=50, verbose_name='code')),
                ('libelle', models.CharField(help_text="Nom officiel et lisible de l'autorisation.", max_length=100, verbose_name='libellé')),
                ('description', models.TextField(blank=True, default='', help_text="Description de l'action ou capacité conférée par cette permission.", verbose_name='description')),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text='Position ordonnée dans les grilles et formulaires de permissions.', verbose_name="ordre d'affichage")),
                ('est_actif', models.BooleanField(default=True, help_text='Indique si cette permission est active et disponible.', verbose_name='est actif')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
                'db_table': 'permission',
                'ordering': ['ordre', 'code'],
            },
        ),
        migrations.AddField(
            model_name='rolemodulepermission',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles_modules', to='accounts.permission', verbose_name='permissions accordées'),
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(condition=models.Q(('supprime_le__isnull', True)), fields=('code',), name='uq_permission_code_actif'),
        ),
        migrations.RunPython(
            seed_permissions_and_migrate_roles,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
