# Generated by Django 5.2.17 on 2026-09-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_rolemodulepermission_niveau_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='modules',
            field=models.ManyToManyField(blank=True, help_text='Modules fonctionnels et applicatifs autorisés à porter cette permission.', related_name='permissions', to='accounts.module', verbose_name='modules éligibles'),
        ),
    ]
