# Generated by Django 5.2.17 on 2026-10-02 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_squashed_0018_seed_permission_modules_m2m'),
        ('catalogue', '0002_peupler_catalogue_depuis_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemodulepermission',
            name='module_catalogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permissions_roles_catalogue', to='catalogue.cataloguemodule', verbose_name='module catalogue'),
        ),
        migrations.AddField(
            model_name='rolemodulepermission',
            name='permissions_catalogue',
            field=models.ManyToManyField(blank=True, db_table='role_module_permission_permissions_catalogue', related_name='roles_modules_catalogue', to='catalogue.cataloguepermission', verbose_name='permissions catalogue accordées'),
        ),
        migrations.AddConstraint(
            model_name='rolemodulepermission',
            constraint=models.UniqueConstraint(condition=models.Q(('module_catalogue__isnull', False), ('supprime_le__isnull', True)), fields=('role', 'module_catalogue'), name='uq_role_module_catalogue_actif'),
        ),
    ]
