# Generated by Django 5.2.17 on 2026-10-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_traduire_niveaux_vers_permissions_catalogue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolemodulepermission',
            name='permissions',
        ),
    ]
