# Generated by Django 5.2.17 on 2026-10-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_migrer_portee_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='email_origine',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="email d'origine"),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role_global',
            field=models.CharField(blank=True, db_index=True, default='VI', max_length=50, verbose_name='rôle global'),
        ),
    ]
