# Generated by Django 5.2.17 on 2026-09-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalPlateforme',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('utilisateur_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='utilisateur plateforme')),
                ('entreprise_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='entreprise')),
                ('action', models.CharField(db_index=True, max_length=50, verbose_name='action')),
                ('detail', models.JSONField(blank=True, null=True, verbose_name='détails')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('appareil', models.CharField(blank=True, max_length=255, verbose_name='appareil')),
                ('horodatage', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='horodatage')),
            ],
            options={
                'verbose_name': 'entrée du journal plateforme',
                'verbose_name_plural': 'journal plateforme',
                'db_table': 'journal_plateforme',
                'ordering': ['-horodatage'],
                'indexes': [models.Index(fields=['entreprise_id', '-horodatage'], name='plat_audit_entr_idx'), models.Index(fields=['utilisateur_id', '-horodatage'], name='plat_audit_user_idx'), models.Index(fields=['action', '-horodatage'], name='plat_audit_act_idx')],
            },
        ),
    ]
