# Generated by Django 5.2.17 on 2026-10-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentitePlateforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='CCD Digital', max_length=120, verbose_name='nom')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='plateforme/', verbose_name='logo')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'identité de la plateforme',
                'verbose_name_plural': 'identité de la plateforme',
                'db_table': 'identite_plateforme',
            },
        ),
    ]
