# Generated by Django 5.2.17 on 2026-09-03 09:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_alter_demandeinscription_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('code', models.CharField(choices=[('STARTER', 'Starter'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], max_length=20, unique=True, verbose_name='code')),
                ('libelle', models.CharField(max_length=100, verbose_name='libellé')),
                ('prix_mensuel_montant', models.BigIntegerField(blank=True, help_text='Centimes FCFA. NULL = non tranché.', null=True, verbose_name='prix mensuel')),
                ('prix_annuel_montant', models.BigIntegerField(blank=True, help_text='Centimes FCFA. NULL = non tranché.', null=True, verbose_name='prix annuel')),
                ('limite_projets', models.IntegerField(blank=True, null=True, verbose_name='limite de projets')),
                ('limite_utilisateurs', models.IntegerField(blank=True, null=True, verbose_name="limite d'utilisateurs")),
                ('limite_stockage_mo', models.IntegerField(blank=True, null=True, verbose_name='limite de stockage (Mo)')),
                ('acces_ia', models.BooleanField(default=False, verbose_name='accès aux fonctions IA')),
                ('limites_avancees', models.JSONField(blank=True, default=dict, verbose_name='limites avancées')),
                ('est_actif', models.BooleanField(default=True, verbose_name='proposé à la vente')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
                'db_table': 'plan',
                'ordering': ['prix_mensuel_montant'],
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_debut', models.DateField(verbose_name='début')),
                ('date_fin', models.DateField(verbose_name='fin')),
                ('fin_essai', models.DateField(blank=True, null=True, verbose_name="fin de l'essai")),
                ('statut', models.CharField(choices=[('ESSAI', 'Essai gratuit'), ('ACTIF', 'Actif'), ('IMPAYE', 'Impayé'), ('SUSPENDU', 'Suspendu'), ('RESILIE', 'Résilié')], default='ESSAI', max_length=20, verbose_name='statut')),
                ('renouvellement_auto', models.BooleanField(default=True, verbose_name='renouvellement automatique')),
                ('lecture_seule_depuis', models.DateTimeField(blank=True, null=True, verbose_name='lecture seule depuis')),
                ('suppression_annoncee_le', models.DateTimeField(blank=True, null=True, verbose_name='suppression annoncée le')),
                ('suppression_prevue_le', models.DateField(blank=True, null=True, verbose_name='suppression prévue le')),
                ('donnees_supprimees_le', models.DateTimeField(blank=True, null=True, verbose_name='données supprimées le')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='abonnements', to='tenants.entreprise')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='abonnements', to='billing.plan')),
            ],
            options={
                'verbose_name': 'abonnement',
                'verbose_name_plural': 'abonnements',
                'db_table': 'abonnement',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('prix_mensuel_montant__gte', 0), ('prix_mensuel_montant__isnull', True), _connector='OR'), name='chk_plan_prix_mensuel_positif'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('prix_annuel_montant__gte', 0), ('prix_annuel_montant__isnull', True), _connector='OR'), name='chk_plan_prix_annuel_positif'),
        ),
        migrations.AddConstraint(
            model_name='abonnement',
            constraint=models.CheckConstraint(condition=models.Q(('date_fin__gt', models.F('date_debut'))), name='chk_abonnement_dates'),
        ),
        migrations.AddConstraint(
            model_name='abonnement',
            constraint=models.UniqueConstraint(condition=models.Q(('statut__in', ['ESSAI', 'ACTIF'])), fields=('entreprise',), name='uq_abonnement_actif'),
        ),
        migrations.AddConstraint(
            model_name='abonnement',
            constraint=models.CheckConstraint(condition=models.Q(('suppression_prevue_le__isnull', True), ('suppression_annoncee_le__isnull', False), _connector='OR'), name='chk_suppression_annoncee'),
        ),
    ]
