# Generated by Django 5.2.17 on 2026-09-09 10:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelanceEssai',
            fields=[
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seuil', models.PositiveSmallIntegerField(verbose_name='seuil en jours')),
                ('destinataires', models.PositiveSmallIntegerField(default=0, verbose_name='destinataires')),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relances_essai', to='billing.abonnement')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': "relance d'essai",
                'verbose_name_plural': "relances d'essai",
                'db_table': 'relance_essai',
                'ordering': ['-cree_le'],
                'constraints': [models.UniqueConstraint(fields=('abonnement', 'seuil'), name='uq_relance_essai_seuil')],
            },
        ),
    ]
