# Generated by Django 5.2.17 on 2026-09-11 11:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_planifier_relances_essai'),
        ('tenants', '0008_logo_forme_naturelle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.CharField(choices=[('BATISSEUR', 'Bâtisseur'), ('MAITRE_OEUVRE', "Maître d'Œuvre"), ('PROMOTEUR', 'Promoteur'), ('STARTER', 'Starter (Ancien)'), ('PRO', 'Pro (Ancien)'), ('ENTERPRISE', 'Enterprise (Ancien)')], max_length=20, unique=True, verbose_name='code'),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(help_text='Numéro séquentiel conforme OHADA, ex: FAC-2026-09-0001', max_length=30, unique=True, verbose_name='numéro')),
                ('periode_debut', models.DateField(verbose_name='période début')),
                ('periode_fin', models.DateField(verbose_name='période fin')),
                ('montant_ht', models.BigIntegerField(verbose_name='montant HT (centimes)')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5, verbose_name='taux TVA (%)')),
                ('montant_tva', models.BigIntegerField(verbose_name='montant TVA (centimes)')),
                ('montant_ttc', models.BigIntegerField(verbose_name='montant TTC (centimes)')),
                ('statut', models.CharField(choices=[('EMISE', 'Émise'), ('PAYEE', 'Payée'), ('IMPAYEE', 'Impayée'), ('ANNULEE', 'Annulée')], db_index=True, default='EMISE', max_length=20, verbose_name='statut')),
                ('date_emission', models.DateField(default=django.utils.timezone.localdate, verbose_name="date d'émission")),
                ('date_echeance', models.DateField(verbose_name="date d'échéance")),
                ('fichier_pdf', models.CharField(blank=True, max_length=500, verbose_name='fichier PDF')),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='factures', to='billing.abonnement', verbose_name='abonnement')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='factures', to='tenants.entreprise', verbose_name='entreprise cliente')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'facture',
                'verbose_name_plural': 'factures',
                'db_table': 'facture',
                'ordering': ['-date_emission', '-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='PaiementAbonnement',
            fields=[
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('ORANGE_MONEY', 'Orange Money'), ('WAVE', 'Wave'), ('MTN_MOMO', 'MTN Mobile Money'), ('MOOV_MONEY', 'Moov Money'), ('CARTE', 'Carte Bancaire (Visa / Mastercard)'), ('VIREMENT', 'Virement Bancaire'), ('AUTRE', 'Autre')], default='AUTRE', max_length=30, verbose_name='mode de paiement')),
                ('reference_commande', models.CharField(max_length=100, unique=True, verbose_name='référence commande')),
                ('reference_transaction', models.CharField(blank=True, help_text='Identifiant de transaction CinetPay, unique et idempotent', max_length=100, null=True, unique=True, verbose_name='référence transaction')),
                ('montant', models.BigIntegerField(help_text='Centimes FCFA', verbose_name='montant')),
                ('statut', models.CharField(choices=[('INITIE', 'Initié'), ('CONFIRME', 'Confirmé'), ('ECHOUE', 'Échoué'), ('REMBOURSE', 'Remboursé')], db_index=True, default='INITIE', max_length=20, verbose_name='statut')),
                ('paye_le', models.DateTimeField(blank=True, null=True, verbose_name='payé le')),
                ('charge_utile', models.JSONField(blank=True, default=dict, help_text='Réponse brute du prestataire conservée pour litige', verbose_name='charge utile prestataire')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='paiements', to='billing.facture', verbose_name='facture')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': "paiement d'abonnement",
                'verbose_name_plural': "paiements d'abonnement",
                'db_table': 'paiement_abonnement',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddConstraint(
            model_name='facture',
            constraint=models.CheckConstraint(condition=models.Q(('montant_ht__gte', 0)), name='chk_facture_montant_ht_positif'),
        ),
        migrations.AddConstraint(
            model_name='facture',
            constraint=models.CheckConstraint(condition=models.Q(('montant_ttc__gte', models.F('montant_ht'))), name='chk_facture_montant_ttc_gte_ht'),
        ),
        migrations.AddConstraint(
            model_name='facture',
            constraint=models.CheckConstraint(condition=models.Q(('periode_fin__gte', models.F('periode_debut'))), name='chk_facture_periodes'),
        ),
        migrations.AddConstraint(
            model_name='paiementabonnement',
            constraint=models.CheckConstraint(condition=models.Q(('montant__gt', 0)), name='chk_paiement_montant_positif'),
        ),
    ]
