# Generated by Django 5.2.17 on 2026-09-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_planifier_verification_paiements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementabonnement',
            name='statut',
            field=models.CharField(choices=[('INITIE', 'Initié'), ('EN_ATTENTE_OPERATEUR', 'En attente opérateur'), ('CONFIRME', 'Confirmé'), ('ANNULE', 'Annulé'), ('EXPIRE', 'Expiré'), ('ECHOUE', 'Échoué'), ('REMBOURSE', 'Remboursé')], db_index=True, default='INITIE', max_length=30, verbose_name='statut'),
        ),
    ]
