# Generated by Django 5.2.17 on 2026-09-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_paiementabonnement_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='contexte_facturation',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
