# Generated by Django 5.2.17 on 2026-09-23 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_facture_contexte_facturation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RappelExpiration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('date_echeance', models.DateField()),
                ('seuil', models.PositiveSmallIntegerField(choices=[(7, '7'), (3, '3'), (1, '1'), (0, '0')])),
                ('destinataire', models.EmailField(max_length=254)),
                ('envoye_le', models.DateTimeField(blank=True, null=True)),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.abonnement')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'db_table': 'rappel_expiration_abonnement',
                'constraints': [models.UniqueConstraint(fields=('abonnement', 'date_echeance', 'seuil', 'destinataire'), name='uq_rappel_expiration_destinataire')],
            },
        ),
    ]
