# Generated by Django 5.2.17 on 2026-09-07 17:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureBon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('niveau_requis', models.CharField(default='DG', max_length=10, verbose_name='niveau requis')),
                ('signe_le', models.DateTimeField(default=django.utils.timezone.now, verbose_name='signé le')),
                ('commentaire', models.TextField(blank=True, verbose_name='commentaire')),
            ],
            options={
                'verbose_name': 'signature de bon',
                'verbose_name_plural': 'signatures de bons',
                'db_table': 'signature_bon',
                'ordering': ['-signe_le'],
            },
        ),
        migrations.CreateModel(
            name='BonPaiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('numero', models.CharField(help_text='ex: BDP-2026-001', max_length=30, verbose_name='numéro / référence')),
                ('corps_etat', models.CharField(blank=True, help_text='ex: Maçonnerie RDC, Électricité, etc.', max_length=150, verbose_name="corps d'état / prestation")),
                ('periode_debut', models.DateField(default=django.utils.timezone.now, verbose_name='période du')),
                ('periode_fin', models.DateField(default=django.utils.timezone.now, verbose_name='période au')),
                ('montant_brut', models.BigIntegerField(default=0, verbose_name='montant brut (centimes)')),
                ('deduction_avance', models.BigIntegerField(default=0, verbose_name='déduction avance (centimes)')),
                ('deduction_penalite', models.BigIntegerField(default=0, verbose_name='déduction pénalité (centimes)')),
                ('montant_net', models.BigIntegerField(default=0, verbose_name='montant net à payer (centimes)')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('A_SIGNER', 'À signer'), ('SIGNE', 'Signé'), ('PAYE', 'Payé'), ('CLOTURE', 'Clôturé')], default='A_SIGNER', max_length=20, verbose_name='statut')),
                ('mode_paiement', models.CharField(choices=[('CASH', 'Espèces'), ('VIREMENT', 'Virement'), ('ORANGE_MONEY', 'Orange Money'), ('WAVE', 'Wave'), ('MTN_MOMO', 'MTN MoMo')], default='VIREMENT', max_length=20, verbose_name='mode de paiement')),
                ('reference_paiement', models.CharField(blank=True, max_length=100, verbose_name='référence de paiement')),
                ('paye_le', models.DateTimeField(blank=True, null=True, verbose_name='payé le')),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bons_paiement', to='tiers.tiers', verbose_name='bénéficiaire (tâcheron / sous-traitant)')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
            ],
            options={
                'verbose_name': 'bon de paiement',
                'verbose_name_plural': 'bons de paiement',
                'db_table': 'bon_paiement',
                'ordering': ['-cree_le'],
            },
        ),
    ]
