# Generated by Django 5.2.17 on 2026-09-07 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('projets', '0005_lot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bonpaiement',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bons_paiement', to='projets.lot', verbose_name='lot de travaux'),
        ),
        migrations.AddField(
            model_name='bonpaiement',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bons_paiement', to='projets.projet', verbose_name='projet / chantier'),
        ),
        migrations.AddField(
            model_name='bonpaiement',
            name='supprime_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par'),
        ),
        migrations.AddField(
            model_name='signaturebon',
            name='bon_paiement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='finance.bonpaiement', verbose_name='bon de paiement'),
        ),
        migrations.AddField(
            model_name='signaturebon',
            name='cree_par',
            field=models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par'),
        ),
        migrations.AddField(
            model_name='signaturebon',
            name='signataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='signatures_bons', to=settings.AUTH_USER_MODEL, verbose_name='signataire'),
        ),
        migrations.AddField(
            model_name='signaturebon',
            name='supprime_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par'),
        ),
        migrations.AddIndex(
            model_name='bonpaiement',
            index=models.Index(fields=['projet', 'statut'], name='idx_bdp_proj_statut'),
        ),
        migrations.AddIndex(
            model_name='bonpaiement',
            index=models.Index(fields=['statut'], name='idx_bdp_statut'),
        ),
    ]
