# Generated by Django 5.2.17 on 2026-08-24 16:06

import django.db.models.deletion
import django_tenants.postgresql_backend.base
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raison_sociale', models.CharField(max_length=200, verbose_name='raison sociale')),
                ('nom_commercial', models.CharField(blank=True, max_length=200, verbose_name='nom commercial')),
                ('pays', models.CharField(default='CI', help_text='Code ISO. Détermine le calendrier des jours fériés applicable.', max_length=2, verbose_name='pays')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('rccm', models.CharField(blank=True, max_length=50, verbose_name='RCCM')),
                ('nif', models.CharField(blank=True, max_length=50, verbose_name='NIF')),
                ('logo', models.CharField(blank=True, max_length=500, verbose_name='logo')),
                ('email_contact', models.EmailField(max_length=254, verbose_name='email de contact')),
                ('telephone_contact', models.CharField(blank=True, max_length=20, verbose_name='téléphone de contact')),
                ('statut', models.CharField(choices=[('ESSAI', "Période d'essai"), ('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('RESILIE', 'Résilié')], db_index=True, default='ESSAI', max_length=20, verbose_name='statut')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="date d'inscription")),
            ],
            options={
                'verbose_name': 'entreprise cliente',
                'verbose_name_plural': 'entreprises clientes',
                'db_table': 'entreprise_cliente',
                'ordering': ['raison_sociale'],
            },
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.entreprise')),
            ],
            options={
                'verbose_name': 'domaine',
                'verbose_name_plural': 'domaines',
                'db_table': 'domaine',
            },
        ),
    ]
