# Generated by Django 5.2.17 on 2026-09-02 18:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeInscription',
            fields=[
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('raison_sociale', models.CharField(max_length=200, verbose_name='raison sociale')),
                ('pays', models.CharField(max_length=2, verbose_name='pays')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('slug_reserve', models.CharField(max_length=40, verbose_name='slug réservé')),
                ('empreinte', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='empreinte')),
                ('expire_le', models.DateTimeField(verbose_name='expire le')),
                ('utilise_le', models.DateTimeField(blank=True, null=True, verbose_name='utilisée le')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', "En attente d'activation"), ('ACTIVEE', 'Activée'), ('ABANDONNEE', 'Abandonnée')], default='EN_ATTENTE', max_length=20, verbose_name='statut')),
                ('nom', models.CharField(blank=True, max_length=100, verbose_name='nom')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='prénom')),
                ('mot_de_passe_transitoire', models.CharField(blank=True, max_length=128, verbose_name='mot de passe transitoire')),
                ('cgu_version', models.CharField(max_length=20, verbose_name='version des CGU')),
                ('cgu_acceptees_le', models.DateTimeField(verbose_name='CGU acceptées le')),
                ('cgu_adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name="IP d'acceptation")),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='demandes', to='tenants.entreprise')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': "demande d'inscription",
                'verbose_name_plural': "demandes d'inscription",
                'db_table': 'demande_inscription',
                'ordering': ['-cree_le'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('statut', 'EN_ATTENTE')), fields=('slug_reserve',), name='uq_demande_slug')],
            },
        ),
    ]
