# Generated by Django 5.2.17 on 2026-09-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_demandeinscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeinscription',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', "En attente d'activation"), ('PROVISIONNEMENT', 'Provisionnement en cours'), ('ACTIVEE', 'Activée'), ('ECHEC', 'Provisionnement en échec'), ('ABANDONNEE', 'Abandonnée')], default='EN_ATTENTE', max_length=20, verbose_name='statut'),
        ),
    ]
