# Generated by Django 5.2.17 on 2026-09-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_demandeinscription_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='adresse',
            field=models.TextField(blank=True, verbose_name='adresse'),
        ),
    ]
