# Generated by Django 5.2.17 on 2026-09-07 11:38

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def dedupliquer_entreprises_existantes(apps, schema_editor):
    Entreprise = apps.get_model('tenants', 'Entreprise')
    vues = set()
    for entreprise in Entreprise.objects.order_by('date_inscription', 'schema_name'):
        cle = (entreprise.raison_sociale.strip().lower(), entreprise.email_contact.strip().lower())
        if cle in vues:
            entreprise.raison_sociale = f"{entreprise.raison_sociale} ({entreprise.schema_name})"
            parties_email = entreprise.email_contact.split('@')
            if len(parties_email) == 2:
                entreprise.email_contact = f"{parties_email[0]}+{entreprise.schema_name}@{parties_email[1]}"
            else:
                entreprise.email_contact = f"{entreprise.email_contact}.{entreprise.schema_name}"
            entreprise.save(update_fields=['raison_sociale', 'email_contact'])
        else:
            vues.add(cle)


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_entreprise_adresse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(dedupliquer_entreprises_existantes, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='demandeinscription',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('raison_sociale'), django.db.models.functions.text.Lower('email'), condition=models.Q(('statut', 'EN_ATTENTE')), name='uq_demande_nom_email_attente'),
        ),
        migrations.AddConstraint(
            model_name='entreprise',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('raison_sociale'), django.db.models.functions.text.Lower('email_contact'), name='uq_entreprise_nom_email'),
        ),
    ]
