# Generated by Django 5.2.17 on 2026-09-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_demandeinscription_uq_demande_nom_email_attente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='couleur_primaire',
            field=models.CharField(blank=True, default='#D4652A', help_text='Code hexadécimal de la couleur primaire pour le white-label.', max_length=7, verbose_name='couleur primaire'),
        ),
    ]
