# Generated by Django 5.2.17 on 2026-09-21 13:59

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_logo_forme_naturelle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='demandeinscription',
            name='uq_demande_nom_email_attente',
        ),
        migrations.RemoveConstraint(
            model_name='entreprise',
            name='uq_entreprise_nom_email',
        ),
        migrations.AddConstraint(
            model_name='demandeinscription',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('statut', 'EN_ATTENTE')), name='uq_demande_email_attente'),
        ),
        migrations.AddConstraint(
            model_name='entreprise',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email_contact'), name='uq_entreprise_email_contact'),
        ),
    ]
