# Generated by Django 5.2.17 on 2026-09-23 16:10

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_remove_demandeinscription_uq_demande_nom_email_attente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='demandeinscription',
            name='uq_demande_slug',
        ),
        migrations.RemoveConstraint(
            model_name='demandeinscription',
            name='uq_demande_email_attente',
        ),
        migrations.AddField(
            model_name='demandeinscription',
            name='decision_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeinscription',
            name='decision_par',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeinscription',
            name='motif_refus',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='demandeinscription',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', "En attente d'activation"), ('A_VALIDER', 'En attente de validation du super admin'), ('REFUSEE', 'Refusee'), ('PROVISIONNEMENT', 'Provisionnement en cours'), ('ACTIVEE', 'Activée'), ('ECHEC', 'Provisionnement en échec'), ('ABANDONNEE', 'Abandonnée')], default='EN_ATTENTE', max_length=20, verbose_name='statut'),
        ),
        migrations.AddConstraint(
            model_name='demandeinscription',
            constraint=models.UniqueConstraint(condition=models.Q(('statut__in', ['EN_ATTENTE', 'A_VALIDER', 'PROVISIONNEMENT'])), fields=('slug_reserve',), name='uq_demande_slug'),
        ),
        migrations.AddConstraint(
            model_name='demandeinscription',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('statut__in', ['EN_ATTENTE', 'A_VALIDER', 'PROVISIONNEMENT'])), name='uq_demande_email_attente'),
        ),
    ]
