# Generated by Django 5.2.17 on 2026-10-07 01:29

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_remove_demandeinscription_uq_demande_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistreEmail',
            fields=[
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='adresse e-mail')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registre_emails', to='tenants.entreprise', verbose_name='entreprise')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'registre e-mail',
                'verbose_name_plural': 'registre e-mails',
                'db_table': 'registre_email',
                'ordering': ['-cree_le'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='uq_registre_email_lower')],
            },
        ),
    ]
