# Generated by Django 5.2.17 on 2026-09-07 17:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projets', '0004_alter_affectationprojet_role_projet'),
        ('tiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptionMateriau',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('designation', models.CharField(help_text='ex: 400 sacs ciment CPJ 42.5 livrés & contrôlés', max_length=255, verbose_name='désignation des matériaux')),
                ('quantite', models.DecimalField(decimal_places=3, default=1, max_digits=14, verbose_name='quantité livrée')),
                ('unite', models.CharField(blank=True, default='U', max_length=20, verbose_name='unité de mesure')),
                ('conforme', models.BooleanField(default=True, verbose_name='conforme aux spécifications')),
                ('date_reception', models.DateField(default=django.utils.timezone.now, verbose_name='date de réception')),
                ('observation', models.TextField(blank=True, verbose_name='observations / réserves éventuelles')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='receptions_fournisseur', to='tiers.tiers', verbose_name='fournisseur / livreur')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='receptions_materiaux', to='projets.projet', verbose_name='projet / chantier')),
                ('receptionne_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='réceptionné par (magasinier / CT)')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'réception de matériau',
                'verbose_name_plural': 'réceptions de matériaux',
                'db_table': 'reception_materiau',
                'ordering': ['-date_reception', '-cree_le'],
                'indexes': [models.Index(fields=['projet', 'date_reception'], name='idx_rec_mat_proj_date')],
            },
        ),
    ]
