# Generated by Django 5.2.17 on 2026-09-03 11:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressionConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('unique_par_schema', models.BooleanField(default=True, editable=False)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée')], default='EN_COURS', max_length=20, verbose_name='statut')),
                ('etape_courante', models.CharField(choices=[('ENTREPRISE', 'Votre entreprise'), ('PROJET', 'Premier projet'), ('EQUIPE', 'Votre équipe')], default='ENTREPRISE', max_length=20, verbose_name='étape courante')),
                ('demarre_le', models.DateTimeField(auto_now_add=True, verbose_name='démarrée le')),
                ('terminee_le', models.DateTimeField(blank=True, null=True, verbose_name='terminée le')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'progression de configuration',
                'verbose_name_plural': 'progressions de configuration',
                'db_table': 'progression_configuration',
            },
        ),
        migrations.CreateModel(
            name='EtapeConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('code', models.CharField(choices=[('ENTREPRISE', 'Votre entreprise'), ('PROJET', 'Premier projet'), ('EQUIPE', 'Votre équipe')], max_length=20, verbose_name='code')),
                ('mode', models.CharField(choices=[('VALIDEE', 'Validée'), ('PASSEE', 'Passée')], max_length=10, verbose_name='mode')),
                ('franchie_le', models.DateTimeField(auto_now_add=True, verbose_name='franchie le')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('franchie_par', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='etapes_franchies', to=settings.AUTH_USER_MODEL)),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('progression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='onboarding.progressionconfiguration')),
            ],
            options={
                'verbose_name': 'étape de configuration',
                'verbose_name_plural': 'étapes de configuration',
                'db_table': 'etape_configuration',
                'ordering': ['franchie_le'],
            },
        ),
        migrations.AddConstraint(
            model_name='progressionconfiguration',
            constraint=models.UniqueConstraint(fields=('unique_par_schema',), name='uq_progression_singleton'),
        ),
        migrations.AddConstraint(
            model_name='progressionconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('unique_par_schema', True)), name='chk_progression_singleton'),
        ),
        migrations.AddConstraint(
            model_name='etapeconfiguration',
            constraint=models.UniqueConstraint(fields=('progression', 'code'), name='uq_etape_configuration'),
        ),
    ]
