# Generated by Django 5.2.17 on 2026-10-02 15:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0010_remove_demandeinscription_uq_demande_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('code', models.CharField(db_index=True, help_text="Code technique unique du module (ex: 'projets', 'chantier', 'ged').", max_length=50, verbose_name='code')),
                ('libelle', models.CharField(help_text='Nom officiel et lisible du module.', max_length=100, verbose_name='libellé')),
                ('description', models.TextField(blank=True, default='', help_text='Périmètre fonctionnel et fonctionnalités couvertes par ce module.', verbose_name='description')),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text='Position ordonnée dans la navigation et les matrices de permissions.', verbose_name="ordre d'affichage")),
                ('icone', models.CharField(blank=True, default='box', help_text="Identifiant de l'icône Lucide / frontend associée.", max_length=50, verbose_name='icône')),
                ('est_actif', models.BooleanField(default=True, help_text='Indique si le module est actif globalement sur la plateforme.', verbose_name='est actif')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'module catalogue',
                'verbose_name_plural': 'modules catalogue',
                'db_table': 'catalogue_module',
                'ordering': ['ordre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CataloguePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('code', models.CharField(db_index=True, help_text="Code technique unique de l'autorisation (ex: 'LECTURE', 'ECRITURE', 'VALIDATION').", max_length=50, verbose_name='code')),
                ('libelle', models.CharField(help_text="Nom officiel et lisible de l'autorisation.", max_length=100, verbose_name='libellé')),
                ('description', models.TextField(blank=True, default='', help_text="Description de l'action ou capacité conférée par cette permission.", verbose_name='description')),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text='Position ordonnée dans les grilles et formulaires de permissions.', verbose_name="ordre d'affichage")),
                ('est_actif', models.BooleanField(default=True, help_text='Indique si cette permission est active et disponible.', verbose_name='est actif')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('modules', models.ManyToManyField(blank=True, db_table='catalogue_permission_modules', help_text='Modules fonctionnels et applicatifs autorisés à porter cette permission.', related_name='permissions', to='catalogue.cataloguemodule', verbose_name='modules éligibles')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'permission catalogue',
                'verbose_name_plural': 'permissions catalogue',
                'db_table': 'catalogue_permission',
                'ordering': ['ordre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='EntrepriseModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('est_actif', models.BooleanField(default=True, help_text='Indique si le module est actif pour cette entreprise.', verbose_name='est actif')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('entreprise', models.ForeignKey(help_text='Entreprise cliente abonnée au module.', on_delete=django.db.models.deletion.CASCADE, related_name='modules_souscrits', to='tenants.entreprise', verbose_name='entreprise')),
                ('module', models.ForeignKey(help_text='Module catalogue souscrit.', on_delete=django.db.models.deletion.PROTECT, related_name='entreprises_associees', to='catalogue.cataloguemodule', verbose_name='module')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': "module souscrit par l'entreprise",
                'verbose_name_plural': 'modules souscrits par les entreprises',
                'db_table': 'catalogue_entreprise_module',
                'ordering': ['entreprise', 'module__ordre'],
            },
        ),
        migrations.AddConstraint(
            model_name='cataloguemodule',
            constraint=models.UniqueConstraint(condition=models.Q(('supprime_le__isnull', True)), fields=('code',), name='uq_catalogue_module_code_actif'),
        ),
        migrations.AddConstraint(
            model_name='cataloguepermission',
            constraint=models.UniqueConstraint(condition=models.Q(('supprime_le__isnull', True)), fields=('code',), name='uq_catalogue_permission_code_actif'),
        ),
        migrations.AddConstraint(
            model_name='entreprisemodule',
            constraint=models.UniqueConstraint(condition=models.Q(('supprime_le__isnull', True)), fields=('entreprise', 'module'), name='uq_entreprise_module_actif'),
        ),
    ]
