# Generated by Django 5.2.17 on 2026-10-04 17:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_peupler_catalogue_depuis_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('code', models.CharField(db_index=True, help_text='Code normalisé du modèle de rôle (ex: DG, AD, DO, DF, CP, CT, CC, MAG, BAI, VI).', max_length=50, verbose_name='code')),
                ('libelle', models.CharField(help_text='Nom officiel du modèle de rôle (ex: Conducteur de Travaux).', max_length=100, verbose_name='libellé')),
                ('description', models.TextField(blank=True, default='', help_text='Responsabilités et périmètre type du rôle.', verbose_name='description')),
                ('est_actif', models.BooleanField(default=True, help_text='Indique si le modèle est disponible pour les nouvelles entreprises.', verbose_name='est actif')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'modèle de rôle',
                'verbose_name_plural': 'modèles de rôles',
                'db_table': 'catalogue_modele_role',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ModeleRoleModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('module_code', models.CharField(blank=True, default='', help_text="Code technique du module (ex: 'projets', 'administration').", max_length=50, verbose_name='code module')),
                ('niveau_max', models.PositiveSmallIntegerField(choices=[(0, 'Aucun'), (1, 'Lecture'), (2, 'Écriture / Saisie'), (3, 'Validation / Approbation')], default=0, help_text='Plafond non franchissable par le tenant : 0 Aucun, 1 Lecture, 2 Écriture, 3 Validation.', verbose_name="niveau d'accès maximum")),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('modele_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_plafonds', to='catalogue.modelerole', verbose_name='modèle de rôle')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plafonds_modeles_roles', to='catalogue.cataloguemodule', verbose_name='module catalogue')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'plafond module du modèle de rôle',
                'verbose_name_plural': 'plafonds modules des modèles de rôles',
                'db_table': 'catalogue_modele_role_module',
                'ordering': ['modele_role', 'module_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='modelerole',
            constraint=models.UniqueConstraint(condition=models.Q(('supprime_le__isnull', True)), fields=('code',), name='uq_catalogue_modele_role_code_actif'),
        ),
        migrations.AddConstraint(
            model_name='modelerolemodule',
            constraint=models.UniqueConstraint(condition=models.Q(('supprime_le__isnull', True)), fields=('modele_role', 'module_code'), name='uq_modele_role_module_actif'),
        ),
    ]
