# Generated by Django 5.2.17 on 2026-10-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_peupler_modeles_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='cataloguepermission',
            name='reservee_administration',
            field=models.BooleanField(default=False, help_text="Indique si cette permission est réservée à l'administration de l'entreprise.", verbose_name='réservée administration'),
        ),
    ]
