# Generated by Django 5.2.17 on 2026-10-05 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_cataloguepermission_reservee_administration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelerolemodule',
            options={'ordering': ['modele_role', 'module_code'], 'verbose_name': 'module du modèle de rôle', 'verbose_name_plural': 'modules des modèles de rôles'},
        ),
        migrations.RemoveField(
            model_name='modelerolemodule',
            name='niveau_max',
        ),
    ]
