# Generated by Django 5.2.17 on 2026-09-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('utilisateur_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='utilisateur')),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('EXPORT', 'Export'), ('VALIDATION', 'Validation'), ('SIGNATURE', 'Signature')], max_length=20, verbose_name='action')),
                ('type_entite', models.CharField(max_length=50, verbose_name="type d'entité")),
                ('entite_id', models.UUIDField(blank=True, null=True, verbose_name="identifiant de l'entité")),
                ('valeur_avant', models.JSONField(blank=True, null=True, verbose_name='valeur avant')),
                ('valeur_apres', models.JSONField(blank=True, null=True, verbose_name='valeur après')),
                ('horodatage', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='horodatage')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('appareil', models.CharField(blank=True, max_length=255, verbose_name='appareil')),
            ],
            options={
                'verbose_name': "entrée du journal d'audit",
                'verbose_name_plural': "journal d'audit",
                'db_table': 'journal_audit',
                'ordering': ['-horodatage'],
                'indexes': [models.Index(fields=['type_entite', 'entite_id'], name='audit_entite_idx'), models.Index(fields=['utilisateur_id', '-horodatage'], name='audit_acteur_idx')],
            },
        ),
    ]
