# Generated by Django 5.2.17 on 2026-09-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalaudit',
            name='action',
            field=models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('EXPORT', 'Export'), ('VALIDATION', 'Validation'), ('SIGNATURE', 'Signature'), ('ASSISTANCE', 'Assistance Super Admin')], max_length=20, verbose_name='action'),
        ),
    ]
