# Generated by Django 5.2.17 on 2026-08-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JourFerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(db_index=True, default='CI', max_length=2, verbose_name='pays')),
                ('date_ferie', models.DateField(verbose_name='date')),
                ('libelle', models.CharField(max_length=100, verbose_name='libellé')),
            ],
            options={
                'verbose_name': 'jour férié',
                'verbose_name_plural': 'jours fériés',
                'db_table': 'jour_ferie',
                'ordering': ['date_ferie'],
                'constraints': [models.UniqueConstraint(fields=('pays', 'date_ferie'), name='uq_jour_ferie')],
            },
        ),
    ]
