# Generated by Django 5.2.17 on 2026-09-07 17:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportJournalier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('date_rapport', models.DateField(default=django.utils.timezone.now, verbose_name='date du rapport')),
                ('meteo', models.CharField(choices=[('ENSOLEILLE', 'Ensoleillé'), ('NUAGEUX', 'Nuageux'), ('PLUIE', 'Pluie'), ('ORAGE', 'Orage')], default='ENSOLEILLE', max_length=20, verbose_name='météo')),
                ('effectif_regie', models.PositiveSmallIntegerField(default=0, verbose_name='effectif régie')),
                ('effectif_tacherons', models.PositiveSmallIntegerField(default=0, verbose_name='effectif tâcherons')),
                ('effectif_present', models.PositiveSmallIntegerField(default=0, verbose_name='effectif total présent')),
                ('observations', models.TextField(blank=True, verbose_name='observations / faits marquants')),
                ('blocages_critiques', models.PositiveSmallIntegerField(default=0, verbose_name='nombre de blocages ou incidents critiques')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté')], default='SOUMIS', max_length=20, verbose_name='statut du rapport')),
                ('soumis_le', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='soumis le')),
                ('valide_le', models.DateTimeField(blank=True, null=True, verbose_name='validé le')),
                ('commentaire_validation', models.TextField(blank=True, verbose_name='commentaire de validation')),
                ('origine', models.CharField(default='WEB', max_length=10, verbose_name='origine')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rapports_rediges', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
            ],
            options={
                'verbose_name': 'rapport journalier',
                'verbose_name_plural': 'rapports journaliers',
                'db_table': 'rapport_journalier',
                'ordering': ['-date_rapport', '-cree_le'],
            },
        ),
    ]
