# Generated by Django 5.2.17 on 2026-09-07 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chantier', '0001_initial'),
        ('projets', '0005_lot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportjournalier',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rapports_journaliers', to='projets.lot', verbose_name='lot spécifique'),
        ),
        migrations.AddField(
            model_name='rapportjournalier',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rapports_journaliers', to='projets.projet', verbose_name='projet / chantier'),
        ),
        migrations.AddField(
            model_name='rapportjournalier',
            name='supprime_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par'),
        ),
        migrations.AddField(
            model_name='rapportjournalier',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_valides', to=settings.AUTH_USER_MODEL, verbose_name='validé par (conducteur de travaux)'),
        ),
        migrations.AddIndex(
            model_name='rapportjournalier',
            index=models.Index(fields=['projet', 'date_rapport'], name='idx_rapport_proj_date'),
        ),
        migrations.AddIndex(
            model_name='rapportjournalier',
            index=models.Index(fields=['statut'], name='idx_rapport_statut'),
        ),
    ]
