# Generated by Django 5.2.17 on 2026-10-05 10:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chantier', '0001_squashed_0003_contraintes_rapport'),
        ('projets', '0024_projet_badge_sante_arretchantier_santeprojetsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('severite', models.CharField(choices=[('MINEUR', 'Mineur'), ('MAJEUR', 'Majeur'), ('CRITIQUE', 'Critique')], default='MINEUR', max_length=20, verbose_name='sévérité')),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('PRIS_EN_CHARGE', 'Pris en charge'), ('RESOLU', 'Résolu')], db_index=True, default='OUVERT', max_length=20, verbose_name='statut')),
                ('ouvert_le', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ouvert le')),
                ('resolu_le', models.DateTimeField(blank=True, null=True, verbose_name='résolu le')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocages', to='projets.lot', verbose_name='lot')),
                ('ouvert_par', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='blocages_ouverts', to=settings.AUTH_USER_MODEL, verbose_name='ouvert par')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocages', to='projets.projet', verbose_name='projet')),
                ('resolu_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='blocages_resolus', to=settings.AUTH_USER_MODEL, verbose_name='résolu par')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'blocage',
                'verbose_name_plural': 'blocages',
                'db_table': 'blocage',
                'ordering': ['-ouvert_le'],
                'indexes': [models.Index(fields=['projet', 'statut'], name='idx_blocage_projet_statut')],
            },
        ),
    ]
