# Generated by Django 5.2.17 on 2026-10-07 22:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chantier", "0004_blocage"),
        ("projets", "0029_merge_20261007_1307"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlerteJournal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                ("modifie_le", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "supprime_le",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Non nul = ligne supprimée logiquement. Jamais de suppression physique.",
                        null=True,
                        verbose_name="supprimé le",
                    ),
                ),
                ("cle", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=30)),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "alerte_journal",
            },
        ),
        migrations.CreateModel(
            name="JournalChantier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                ("modifie_le", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "supprime_le",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Non nul = ligne supprimée logiquement. Jamais de suppression physique.",
                        null=True,
                        verbose_name="supprimé le",
                    ),
                ),
                ("saisie", models.JSONField(default=dict)),
                ("photographie", models.JSONField(default=dict)),
                ("valide_ct_le", models.DateTimeField(blank=True, null=True)),
                ("commentaire_ct", models.TextField(blank=True)),
                ("relance_le", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "journal_chantier",
            },
        ),
        migrations.RemoveConstraint(
            model_name="rapportjournalier",
            name="uq_rapport_lot_date",
        ),
        migrations.RemoveConstraint(
            model_name="rapportjournalier",
            name="uq_rapport_projet_date",
        ),
        migrations.AddConstraint(
            model_name="rapportjournalier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("lot__isnull", False), ("supprime_le__isnull", True)),
                fields=("lot", "date_rapport"),
                name="uq_rapport_lot_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="rapportjournalier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("lot__isnull", True), ("supprime_le__isnull", True)),
                fields=("projet", "date_rapport"),
                name="uq_rapport_projet_date",
            ),
        ),
        migrations.AddField(
            model_name="alertejournal",
            name="cree_par",
            field=models.ForeignKey(
                blank=True,
                help_text="Nul lorsque l'écriture vient du système.",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="créé par",
            ),
        ),
        migrations.AddField(
            model_name="alertejournal",
            name="destinataires",
            field=models.ManyToManyField(
                related_name="alertes_journal", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="alertejournal",
            name="supprime_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="supprimé par",
            ),
        ),
        migrations.AddField(
            model_name="journalchantier",
            name="cree_par",
            field=models.ForeignKey(
                blank=True,
                help_text="Nul lorsque l'écriture vient du système.",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="créé par",
            ),
        ),
        migrations.AddField(
            model_name="journalchantier",
            name="rapport",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="journal",
                to="chantier.rapportjournalier",
            ),
        ),
        migrations.AddField(
            model_name="journalchantier",
            name="supprime_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="supprimé par",
            ),
        ),
        migrations.AddField(
            model_name="journalchantier",
            name="valide_ct_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="journaux_valides_ct",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alertejournal",
            name="journal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="alertes",
                to="chantier.journalchantier",
            ),
        ),
        migrations.AddConstraint(
            model_name="alertejournal",
            constraint=models.UniqueConstraint(
                fields=("journal", "cle"), name="uq_alerte_journal_cle"
            ),
        ),
    ]
