# Generated by Django 5.2.17 on 2026-09-03 15:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('reference', models.CharField(max_length=30, verbose_name='référence')),
                ('nom', models.CharField(max_length=200, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('ville', models.CharField(max_length=100, verbose_name='ville')),
                ('quartier', models.CharField(blank=True, max_length=150, verbose_name='quartier')),
                ('budget_initial_montant', models.BigIntegerField(default=0, help_text='Montant en centimes de FCFA.', verbose_name='budget initial (centimes)')),
                ('date_debut_prevue', models.DateField(verbose_name='date de début prévue')),
                ('date_fin_prevue', models.DateField(verbose_name='date de fin prévue')),
                ('date_debut_reelle', models.DateField(blank=True, null=True, verbose_name='date de début réelle')),
                ('date_fin_reelle', models.DateField(blank=True, null=True, verbose_name='date de fin réelle')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('EN_RETARD', 'En retard'), ('CRITIQUE', 'Critique'), ('SUSPENDU', 'Suspendu'), ('TERMINE', 'Terminé'), ('ARCHIVE', 'Archivé')], default='EN_ATTENTE', max_length=20, verbose_name='statut')),
                ('avancement_reel', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='avancement réel (%)')),
                ('avancement_theorique', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='avancement théorique (%)')),
                ('indice_sante', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='indice de santé')),
                ('indice_sante_calcule_le', models.DateTimeField(blank=True, null=True)),
                ('chef_projet', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='projets_geres', to=settings.AUTH_USER_MODEL, verbose_name='chef de projet')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='projets', to='tiers.tiers', verbose_name="client / maître d'ouvrage")),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'projet',
                'verbose_name_plural': 'projets',
                'db_table': 'projet',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='AffectationProjet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('role_projet', models.CharField(choices=[('CP', 'Chef de Projet'), ('CT', 'Conducteur de Travaux'), ('CC', 'Chef de Chantier'), ('VI', 'Visiteur')], default='CP', max_length=5, verbose_name='rôle sur le projet')),
                ('date_debut', models.DateField(default=django.utils.timezone.now, verbose_name='date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('est_actif', models.BooleanField(default=True, verbose_name='est actif')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='projets.projet')),
            ],
            options={
                'verbose_name': 'affectation au projet',
                'verbose_name_plural': 'affectations aux projets',
                'db_table': 'affectation_projet',
                'constraints': [models.UniqueConstraint(fields=('utilisateur', 'projet'), name='uq_affectation_utilisateur_projet')],
            },
        ),
    ]
