# Generated by Django 5.2.17 on 2026-10-02 11:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def migrer_overrides_vers_fk(apps, schema_editor):
    ProjetRoleModuleOverride = apps.get_model("projets", "ProjetRoleModuleOverride")
    Module = apps.get_model("accounts", "Module")
    modules_map = {m.code: m for m in Module.objects.all()}

    for override in ProjetRoleModuleOverride.objects.all():
        mod = modules_map.get(override.module)
        if mod:
            override.module_fk = mod
            override.save(update_fields=["module_fk"])
        else:
            override.delete()


def migrer_overrides_vers_charfield(apps, schema_editor):
    ProjetRoleModuleOverride = apps.get_model("projets", "ProjetRoleModuleOverride")
    for override in ProjetRoleModuleOverride.objects.all():
        if override.module_fk_id:
            Module = apps.get_model("accounts", "Module")
            mod = Module.objects.filter(id=override.module_fk_id).first()
            if mod:
                override.module = mod.code
                override.save(update_fields=["module"])


def seed_motifs_et_baselines(apps, schema_editor):
    MotifReport = apps.get_model("projets", "MotifReport")
    Projet = apps.get_model("projets", "Projet")
    Lot = apps.get_model("projets", "Lot")

    motifs_defaut = [
        {"code": "INTEMPERIES", "libelle": "Intempéries", "ordre": 1, "description": "Fortes pluies, inondations ou intempéries bloquantes."},
        {"code": "CLIENT", "libelle": "Client", "ordre": 2, "description": "Retard de validation, modification des plans ou demande client."},
        {"code": "TECHNIQUE", "libelle": "Technique", "ordre": 3, "description": "Aléa géotechnique, panne matérielle ou contrainte structurelle."},
        {"code": "ADMINISTRATIF", "libelle": "Administratif", "ordre": 4, "description": "Attente d'autorisation administrative ou permis."},
        {"code": "AUTRE", "libelle": "Autre", "ordre": 5, "description": "Autre motif exceptionnel tracé et justifié."},
    ]

    for m in motifs_defaut:
        MotifReport.objects.get_or_create(
            code=m["code"],
            defaults={
                "libelle": m["libelle"],
                "ordre": m["ordre"],
                "description": m["description"],
                "est_actif": True,
            },
        )

    for p in Projet.objects.all():
        updated = False
        if p.date_debut_baseline is None and p.date_debut_prevue:
            p.date_debut_baseline = p.date_debut_prevue
            updated = True
        if p.date_fin_baseline is None and p.date_fin_prevue:
            p.date_fin_baseline = p.date_fin_prevue
            updated = True
        if updated:
            p.save(update_fields=["date_debut_baseline", "date_fin_baseline"])

    for l in Lot.objects.all():
        updated = False
        if l.date_debut_baseline is None and l.date_debut_prevue:
            l.date_debut_baseline = l.date_debut_prevue
            updated = True
        if l.date_fin_baseline is None and l.date_fin_prevue:
            l.date_fin_baseline = l.date_fin_prevue
            updated = True
        if updated:
            l.save(update_fields=["date_debut_baseline", "date_fin_baseline"])


def revert_seed(apps, schema_editor):
    MotifReport = apps.get_model("projets", "MotifReport")
    MotifReport.objects.filter(code__in=["INTEMPERIES", "CLIENT", "TECHNIQUE", "ADMINISTRATIF", "AUTRE"]).delete()


class Migration(migrations.Migration):

    replaces = [('projets', '0001_initial'), ('projets', '0002_affectationprojet_role_projetrolemoduleoverride'), ('projets', '0003_alter_projet_budget_initial_montant'), ('projets', '0004_alter_affectationprojet_role_projet'), ('projets', '0005_lot'), ('projets', '0006_lot_type_bordereau_projet_conducteur_travaux_and_more'), ('projets', '0007_alter_affectationprojet_role_projet_and_more'), ('projets', '0008_projetrolemoduleoverride_module_fk'), ('projets', '0009_projetrolemoduleoverride_permissions_and_more'), ('projets', '0010_lot_date_debut_baseline_lot_date_fin_baseline_and_more'), ('projets', '0011_seed_motifs_et_baseline'), ('projets', '0012_add_ecart_jours_and_indexes'), ('projets', '0013_alter_projet_chef_projet'), ('projets', '0008_projet_maitre_ouvrage_alter_projet_client'), ('projets', '0009_identification_projet'), ('projets', '0014_merge_20261001_1622'), ('projets', '0015_harmonisation_creation_projet')]

    dependencies = [
        ('accounts', '0005_role_utilisateur_role_personnalise_and_more'),
        ('accounts', '0014_rolemodulepermission_module_fk'),
        ('accounts', '0015_alter_rolemodulepermission_niveau_permission_and_more'),
        ('tiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('reference', models.CharField(max_length=30, verbose_name='référence')),
                ('nom', models.CharField(max_length=200, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('ville', models.CharField(max_length=100, verbose_name='ville')),
                ('quartier', models.CharField(blank=True, max_length=150, verbose_name='quartier')),
                ('budget_initial_montant', models.BigIntegerField(blank=True, default=None, help_text='Montant en centimes de FCFA. Facultatif à la création.', null=True, verbose_name='budget initial (centimes)')),
                ('date_debut_prevue', models.DateField(verbose_name='date de début prévue')),
                ('date_fin_prevue', models.DateField(verbose_name='date de fin prévue')),
                ('date_debut_reelle', models.DateField(blank=True, null=True, verbose_name='date de début réelle')),
                ('date_fin_reelle', models.DateField(blank=True, null=True, verbose_name='date de fin réelle')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('EN_RETARD', 'En retard'), ('CRITIQUE', 'Critique'), ('SUSPENDU', 'Suspendu'), ('TERMINE', 'Terminé'), ('ARCHIVE', 'Archivé')], default='EN_ATTENTE', max_length=20, verbose_name='statut')),
                ('avancement_reel', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='avancement réel (%)')),
                ('avancement_theorique', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='avancement théorique (%)')),
                ('indice_sante', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='indice de santé')),
                ('indice_sante_calcule_le', models.DateTimeField(blank=True, null=True)),
                ('chef_projet', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='projets_geres', to=settings.AUTH_USER_MODEL, verbose_name='chef de projet')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='projets', to='tiers.tiers', verbose_name="client / maître d'ouvrage")),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('conducteur_travaux', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='projets_chantiers', to=settings.AUTH_USER_MODEL, verbose_name='conducteur de travaux')),
                ('maitre_oeuvre', models.CharField(blank=True, help_text="Cabinet ou bureau d'études (optionnel).", max_length=200, verbose_name="maître d'œuvre")),
                ('type_projet', models.CharField(choices=[('BATIMENT_RESIDENTIEL', 'Bâtiment — Résidentiel'), ('BATIMENT_COMMERCIAL', 'Bâtiment — Commercial'), ('TP_ROUTE', 'TP — Route'), ('TP_GENIE_CIVIL', 'TP — Génie civil'), ('VRD', 'VRD'), ('INFRASTRUCTURE_INDUSTRIELLE', 'Infrastructure industrielle')], default='BATIMENT_RESIDENTIEL', max_length=40, verbose_name='type de projet')),
            ],
            options={
                'verbose_name': 'projet',
                'verbose_name_plural': 'projets',
                'db_table': 'projet',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='ProjetRoleModuleOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('module', models.CharField(choices=[('projets', 'Gestion des Projets'), ('chantier', 'Suivi Technique / Chantier'), ('finance', 'Gestion Financière'), ('achats', 'Achats & Approvisionnements'), ('stocks', 'Gestion des Stocks'), ('rh', 'Ressources Humaines'), ('equipements', 'Matériel & Équipements'), ('qhse', 'QHSE'), ('contrats', 'Contrats & Sous-traitance'), ('tiers', 'Parties Prenantes / Tiers'), ('ged', 'Gestion Documentaire (GED)'), ('pilotage', 'Pilotage & Tableaux de bord')], max_length=30, verbose_name='module')),
                ('niveau', models.PositiveSmallIntegerField(choices=[(0, 'Aucun'), (1, 'Lecture'), (2, 'Écriture / Saisie'), (3, 'Validation / Approbation')], verbose_name="niveau d'accès sur ce projet")),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides_permissions', to='projets.projet', verbose_name='projet')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides_projets', to='accounts.role', verbose_name='rôle')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'surcharge de permission sur projet',
                'verbose_name_plural': 'surcharges de permissions sur projets',
                'db_table': 'projet_role_module_override',
                'constraints': [models.UniqueConstraint(condition=models.Q(('supprime_le__isnull', True)), fields=('projet', 'role', 'module'), name='uq_projet_role_module_actif')],
            },
        ),
        migrations.CreateModel(
            name='AffectationProjet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('role_projet', models.CharField(choices=[('DP', 'Directeur de Projet'), ('CP', 'Chef de Projet'), ('CT', 'Conducteur de Travaux'), ('CC', 'Chef de Chantier'), ('MOA', "Maître d'Ouvrage (Client)"), ('VI', 'Visiteur')], default='CP', max_length=5, verbose_name='rôle sur le projet')),
                ('date_debut', models.DateField(default=django.utils.timezone.now, verbose_name='date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('est_actif', models.BooleanField(default=True, verbose_name='est actif')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='projets.projet')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_projets', to='accounts.role', verbose_name='rôle personnalisé')),
            ],
            options={
                'verbose_name': 'affectation au projet',
                'verbose_name_plural': 'affectations aux projets',
                'db_table': 'affectation_projet',
                'constraints': [models.UniqueConstraint(fields=('utilisateur', 'projet'), name='uq_affectation_utilisateur_projet')],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('libelle', models.CharField(max_length=200, verbose_name='libellé')),
                ('phase', models.CharField(blank=True, max_length=100, verbose_name='phase')),
                ('mode_execution', models.CharField(choices=[('REGIE', 'Régie'), ('SOUS_TRAITANCE_STRUCTUREE', 'Sous-traitance structurée'), ('SOUS_TRAITANCE_INFORMELLE', 'Sous-traitance informelle')], default='REGIE', max_length=30, verbose_name="mode d'exécution")),
                ('premier_rapport_soumis', models.BooleanField(default=False, verbose_name='premier rapport soumis')),
                ('ordre', models.IntegerField(default=1, verbose_name='ordre')),
                ('date_debut_prevue', models.DateField(blank=True, null=True, verbose_name='date de début prévue')),
                ('date_fin_prevue', models.DateField(blank=True, null=True, verbose_name='date de fin prévue')),
                ('date_debut_reelle', models.DateField(blank=True, null=True, verbose_name='date de début réelle')),
                ('date_fin_reelle', models.DateField(blank=True, null=True, verbose_name='date de fin réelle')),
                ('avancement', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='avancement (%)')),
                ('est_actif', models.BooleanField(default=True, verbose_name='est actif')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lots', to='projets.projet', verbose_name='projet')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('titulaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lots_titulaire', to='tiers.tiers', verbose_name='titulaire / exécutant')),
                ('type_bordereau', models.CharField(choices=[('FORFAIT', 'Forfait'), ('PRIX_UNITAIRE', 'Prix unitaire'), ('MIXTE', 'Mixte')], default='FORFAIT', max_length=20, verbose_name='type de bordereau')),
            ],
            options={
                'verbose_name': 'lot',
                'verbose_name_plural': 'lots',
                'db_table': 'lot',
                'ordering': ['projet', 'ordre', 'code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('supprime_le__isnull', True)), fields=('projet', 'code'), name='uq_lot_code')],
            },
        ),
        migrations.AddConstraint(
            model_name='projet',
            constraint=models.UniqueConstraint(condition=models.Q(('supprime_le__isnull', True)), fields=('reference',), name='uq_projet_reference_tenant'),
        ),
        migrations.AlterField(
            model_name='affectationprojet',
            name='role_projet',
            field=models.CharField(choices=[('CP', 'Chef de Projet'), ('CT', 'Conducteur de Travaux'), ('CC', 'Chef de Chantier'), ('MOA', "Maître d'Ouvrage (Client)"), ('MOE', "Maître d'Œuvre"), ('VI', 'Consultant lecture')], default='CP', max_length=5, verbose_name='rôle sur le projet'),
        ),
        migrations.AlterField(
            model_name='projetrolemoduleoverride',
            name='module',
            field=models.CharField(choices=[('projets', 'Gestion des Projets'), ('chantier', 'Suivi Technique / Chantier'), ('ged', 'Gestion Documentaire (GED)'), ('pilotage', 'Tableaux de bord & Pilotage'), ('tiers', 'Parties Prenantes / Tiers')], max_length=30, verbose_name='module'),
        ),
        migrations.AddField(
            model_name='projetrolemoduleoverride',
            name='module_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overrides_projets', to='accounts.module', verbose_name='module'),
        ),
        migrations.RunPython(
            code=migrer_overrides_vers_fk,
            reverse_code=migrer_overrides_vers_charfield,
        ),
        migrations.RemoveConstraint(
            model_name='projetrolemoduleoverride',
            name='uq_projet_role_module_actif',
        ),
        migrations.RemoveField(
            model_name='projetrolemoduleoverride',
            name='module',
        ),
        migrations.RenameField(
            model_name='projetrolemoduleoverride',
            old_name='module_fk',
            new_name='module',
        ),
        migrations.AlterField(
            model_name='projetrolemoduleoverride',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides_projets', to='accounts.module', verbose_name='module'),
        ),
        migrations.AddConstraint(
            model_name='projetrolemoduleoverride',
            constraint=models.UniqueConstraint(condition=models.Q(('supprime_le__isnull', True)), fields=('projet', 'role', 'module'), name='uq_projet_role_module_actif'),
        ),
        migrations.AddField(
            model_name='projetrolemoduleoverride',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='overrides_projets', to='accounts.permission', verbose_name='permissions accordées sur ce projet'),
        ),
        migrations.AlterField(
            model_name='projetrolemoduleoverride',
            name='niveau',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Aucun'), (1, 'Lecture'), (2, 'Écriture / Saisie'), (3, 'Validation / Approbation')], null=True, verbose_name="niveau d'accès sur ce projet"),
        ),
        migrations.AddField(
            model_name='lot',
            name='date_debut_baseline',
            field=models.DateField(blank=True, help_text='Date de début contractuelle initiale (figée, intacte).', null=True, verbose_name='date de début baseline v0'),
        ),
        migrations.AddField(
            model_name='lot',
            name='date_fin_baseline',
            field=models.DateField(blank=True, help_text='Date de fin contractuelle initiale (figée, intacte).', null=True, verbose_name='date de fin baseline v0'),
        ),
        migrations.AddField(
            model_name='projet',
            name='date_debut_baseline',
            field=models.DateField(blank=True, help_text='Date de début contractuelle initiale (figée, intacte).', null=True, verbose_name='date de début baseline v0'),
        ),
        migrations.AddField(
            model_name='projet',
            name='date_fin_baseline',
            field=models.DateField(blank=True, help_text='Date de fin contractuelle initiale (figée, intacte).', null=True, verbose_name='date de fin baseline v0'),
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('libelle', models.CharField(max_length=200, verbose_name='libellé')),
                ('unite', models.CharField(choices=[('M2', 'm²'), ('ML', 'ml'), ('M3', 'm³'), ('KG', 'kg'), ('U', 'u'), ('FORFAIT', 'forfait')], default='U', max_length=10, verbose_name='unité de mesure')),
                ('quantite_prevue', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='quantité prévue')),
                ('quantite_realisee', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='quantité réalisée')),
                ('avancement', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='avancement (%)')),
                ('poids', models.DecimalField(blank=True, decimal_places=3, help_text="Pondération dans l'avancement du lot ; par défaut la quantité.", max_digits=8, null=True, verbose_name='poids / pondération')),
                ('date_debut_prevue', models.DateField(verbose_name='date de début prévue')),
                ('date_fin_prevue', models.DateField(verbose_name='date de fin prévue')),
                ('date_debut_baseline', models.DateField(blank=True, help_text='Date de début contractuelle initiale (figée, intacte).', null=True, verbose_name='date de début baseline v0')),
                ('date_fin_baseline', models.DateField(blank=True, help_text='Date de fin contractuelle initiale (figée, intacte).', null=True, verbose_name='date de fin baseline v0')),
                ('ordre', models.IntegerField(default=1, verbose_name='ordre')),
                ('est_actif', models.BooleanField(default=True, verbose_name='est actif')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='projets.lot', verbose_name='lot')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'activité',
                'verbose_name_plural': 'activités',
                'db_table': 'activite',
                'ordering': ['lot', 'ordre', 'cree_le'],
            },
        ),
        migrations.CreateModel(
            name='MotifReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('code', models.CharField(help_text='Code unique du motif (ex: INTEMPERIES, CLIENT, etc.).', max_length=50, verbose_name='code')),
                ('libelle', models.CharField(help_text='Nom lisible affiché aux utilisateurs.', max_length=150, verbose_name='libellé')),
                ('description', models.TextField(blank=True, default='', help_text="Explications ou conditions d'application de ce motif.", verbose_name='description')),
                ('est_actif', models.BooleanField(default=True, help_text="Désactiver pour masquer dans les formulaires sans briser l'historique.", verbose_name='est actif')),
                ('ordre', models.PositiveIntegerField(default=1, verbose_name="ordre d'affichage")),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'motif de report',
                'verbose_name_plural': 'motifs de report',
                'db_table': 'motif_report',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('type_objet', models.CharField(choices=[('PROJET', 'Projet'), ('LOT', 'Lot'), ('ACTIVITE', 'Activité')], max_length=20, verbose_name="type d'objet")),
                ('champ', models.CharField(help_text='Nom du champ de date modifié (ex: date_fin_prevue).', max_length=50, verbose_name='champ modifié')),
                ('valeur_avant', models.DateField(verbose_name='valeur avant')),
                ('valeur_apres', models.DateField(verbose_name='valeur après')),
                ('justification', models.TextField(help_text="Justification textuelle d'au moins 30 caractères (RG-11).", verbose_name='justification')),
                ('activite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique_dates', to='projets.activite', verbose_name='activité')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='modifications_dates', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique_dates', to='projets.lot', verbose_name='lot')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique_dates', to='projets.projet', verbose_name='projet')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('motif', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='historique_dates', to='projets.motifreport', verbose_name='motif de report')),
            ],
            options={
                'verbose_name': 'historique de date',
                'verbose_name_plural': 'historiques de dates',
                'db_table': 'historique_date',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddConstraint(
            model_name='activite',
            constraint=models.CheckConstraint(condition=models.Q(('date_fin_prevue__gte', models.F('date_debut_prevue'))), name='chk_activite_dates_coherentes'),
        ),
        migrations.AddConstraint(
            model_name='activite',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('unite', 'FORFAIT'), _negated=True), ('quantite_prevue', Decimal('1.000')), _connector='OR'), name='chk_activite_forfait'),
        ),
        migrations.AddConstraint(
            model_name='motifreport',
            constraint=models.UniqueConstraint(condition=models.Q(('supprime_le__isnull', True)), fields=('code',), name='uq_motif_report_code_actif'),
        ),
        migrations.AddConstraint(
            model_name='historiquedate',
            constraint=models.CheckConstraint(condition=models.Q(('justification__regex', '^[\\s\\S]{30,}$')), name='chk_historique_date_justification_min_30'),
        ),
        migrations.RunPython(
            code=seed_motifs_et_baselines,
            reverse_code=revert_seed,
        ),
        migrations.AddField(
            model_name='historiquedate',
            name='ecart_jours',
            field=models.IntegerField(default=0, help_text="Différence en jours entre la nouvelle date et l'ancienne (valeur_après - valeur_avant).", verbose_name='écart en jours'),
        ),
        migrations.AddIndex(
            model_name='historiquedate',
            index=models.Index(fields=['type_objet', 'champ'], name='hist_date_type_champ_idx'),
        ),
        migrations.AddIndex(
            model_name='historiquedate',
            index=models.Index(fields=['projet', '-cree_le'], name='hist_date_projet_idx'),
        ),
        migrations.AddIndex(
            model_name='historiquedate',
            index=models.Index(fields=['auteur', '-cree_le'], name='hist_date_auteur_idx'),
        ),
        migrations.AddIndex(
            model_name='historiquedate',
            index=models.Index(fields=['ecart_jours'], name='hist_date_ecart_idx'),
        ),
        migrations.RunSQL(
            sql="\n            CREATE OR REPLACE FUNCTION verifier_immuabilite_historique_date()\n            RETURNS TRIGGER AS $$\n            BEGIN\n                RAISE EXCEPTION 'RG-07 : La table historique_date est strictement immuable (append-only). Opération % interdite.', TG_OP;\n            END;\n            $$ LANGUAGE plpgsql;\n\n            DROP TRIGGER IF EXISTS trg_historique_date_immuable ON historique_date;\n            CREATE TRIGGER trg_historique_date_immuable\n            BEFORE UPDATE OR DELETE ON historique_date\n            FOR EACH ROW\n            EXECUTE FUNCTION verifier_immuabilite_historique_date();\n            ",
            reverse_sql='\n            DROP TRIGGER IF EXISTS trg_historique_date_immuable ON historique_date;\n            DROP FUNCTION IF EXISTS verifier_immuabilite_historique_date();\n            ',
        ),
        migrations.AddField(
            model_name='projet',
            name='maitre_ouvrage',
            field=models.CharField(blank=True, max_length=200, verbose_name="maître d'ouvrage"),
        ),
        migrations.AlterField(
            model_name='projet',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='projets', to='tiers.tiers', verbose_name="client / maître d'ouvrage"),
        ),
        migrations.AlterField(
            model_name='projet',
            name='date_debut_prevue',
            field=models.DateField(blank=True, null=True, verbose_name='date de début prévue'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='date_fin_prevue',
            field=models.DateField(blank=True, null=True, verbose_name='date de fin prévue'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='chef_projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_geres', to=settings.AUTH_USER_MODEL, verbose_name='chef de projet'),
        ),
    ]
