# Generated by Django 5.2.17 on 2026-09-04 14:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_role_utilisateur_role_personnalise_and_more'),
        ('projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationprojet',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_projets', to='accounts.role', verbose_name='rôle personnalisé'),
        ),
        migrations.CreateModel(
            name='ProjetRoleModuleOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('module', models.CharField(choices=[('projets', 'Gestion des Projets'), ('chantier', 'Suivi Technique / Chantier'), ('finance', 'Gestion Financière'), ('achats', 'Achats & Approvisionnements'), ('stocks', 'Gestion des Stocks'), ('rh', 'Ressources Humaines'), ('equipements', 'Matériel & Équipements'), ('qhse', 'QHSE'), ('contrats', 'Contrats & Sous-traitance'), ('tiers', 'Parties Prenantes / Tiers'), ('ged', 'Gestion Documentaire (GED)'), ('pilotage', 'Pilotage & Tableaux de bord')], max_length=30, verbose_name='module')),
                ('niveau', models.PositiveSmallIntegerField(choices=[(0, 'Aucun'), (1, 'Lecture'), (2, 'Écriture / Saisie'), (3, 'Validation / Approbation')], verbose_name="niveau d'accès sur ce projet")),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides_permissions', to='projets.projet', verbose_name='projet')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides_projets', to='accounts.role', verbose_name='rôle')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'surcharge de permission sur projet',
                'verbose_name_plural': 'surcharges de permissions sur projets',
                'db_table': 'projet_role_module_override',
                'constraints': [models.UniqueConstraint(condition=models.Q(('supprime_le__isnull', True)), fields=('projet', 'role', 'module'), name='uq_projet_role_module_actif')],
            },
        ),
    ]
