# Generated by Django 5.2.17 on 2026-09-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_affectationprojet_role_projetrolemoduleoverride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='budget_initial_montant',
            field=models.BigIntegerField(blank=True, default=None, help_text='Montant en centimes de FCFA. Facultatif à la création.', null=True, verbose_name='budget initial (centimes)'),
        ),
    ]
