# Generated by Django 5.2.17 on 2026-09-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0003_alter_projet_budget_initial_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectationprojet',
            name='role_projet',
            field=models.CharField(choices=[('DP', 'Directeur de Projet'), ('CP', 'Chef de Projet'), ('CT', 'Conducteur de Travaux'), ('CC', 'Chef de Chantier'), ('IT', 'Ingénieur / Technicien'), ('MAG', 'Magasinier'), ('ST', 'Sous-traitant'), ('FRN', 'Fournisseur'), ('MOA', "Maître d'Ouvrage (Client)"), ('VI', 'Visiteur')], default='CP', max_length=5, verbose_name='rôle sur le projet'),
        ),
    ]
