# Generated by Django 5.2.17 on 2026-09-07 17:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0004_alter_affectationprojet_role_projet'),
        ('tiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('libelle', models.CharField(max_length=200, verbose_name='libellé')),
                ('phase', models.CharField(blank=True, max_length=100, verbose_name='phase')),
                ('mode_execution', models.CharField(choices=[('REGIE', 'Régie'), ('SOUS_TRAITANCE_STRUCTUREE', 'Sous-traitance structurée'), ('SOUS_TRAITANCE_INFORMELLE', 'Sous-traitance informelle')], default='REGIE', max_length=30, verbose_name="mode d'exécution")),
                ('premier_rapport_soumis', models.BooleanField(default=False, verbose_name='premier rapport soumis')),
                ('ordre', models.IntegerField(default=1, verbose_name='ordre')),
                ('date_debut_prevue', models.DateField(blank=True, null=True, verbose_name='date de début prévue')),
                ('date_fin_prevue', models.DateField(blank=True, null=True, verbose_name='date de fin prévue')),
                ('date_debut_reelle', models.DateField(blank=True, null=True, verbose_name='date de début réelle')),
                ('date_fin_reelle', models.DateField(blank=True, null=True, verbose_name='date de fin réelle')),
                ('avancement', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='avancement (%)')),
                ('est_actif', models.BooleanField(default=True, verbose_name='est actif')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lots', to='projets.projet', verbose_name='projet')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('titulaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lots_titulaire', to='tiers.tiers', verbose_name='titulaire / exécutant')),
            ],
            options={
                'verbose_name': 'lot',
                'verbose_name_plural': 'lots',
                'db_table': 'lot',
                'ordering': ['projet', 'ordre', 'code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('supprime_le__isnull', True)), fields=('projet', 'code'), name='uq_lot_code')],
            },
        ),
    ]
