# Generated by Django 5.2.17 on 2026-09-25 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0005_lot'),
        ('tiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='type_bordereau',
            field=models.CharField(choices=[('FORFAIT', 'Forfait'), ('PRIX_UNITAIRE', 'Prix unitaire'), ('MIXTE', 'Mixte')], default='FORFAIT', max_length=20, verbose_name='type de bordereau'),
        ),
        migrations.AddField(
            model_name='projet',
            name='conducteur_travaux',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='projets_chantiers', to=settings.AUTH_USER_MODEL, verbose_name='conducteur de travaux'),
        ),
        migrations.AddField(
            model_name='projet',
            name='maitre_oeuvre',
            field=models.CharField(blank=True, help_text="Cabinet ou bureau d'études (optionnel).", max_length=200, verbose_name="maître d'œuvre"),
        ),
        migrations.AddField(
            model_name='projet',
            name='type_projet',
            field=models.CharField(choices=[('BATIMENT_RESIDENTIEL', 'Bâtiment — Résidentiel'), ('BATIMENT_COMMERCIAL', 'Bâtiment — Commercial'), ('TP_ROUTE', 'TP — Route'), ('TP_GENIE_CIVIL', 'TP — Génie civil'), ('VRD', 'VRD'), ('INFRASTRUCTURE_INDUSTRIELLE', 'Infrastructure industrielle')], default='BATIMENT_RESIDENTIEL', max_length=40, verbose_name='type de projet'),
        ),
        migrations.AddConstraint(
            model_name='projet',
            constraint=models.UniqueConstraint(condition=models.Q(('supprime_le__isnull', True)), fields=('reference',), name='uq_projet_reference_tenant'),
        ),
    ]
