# Generated by Django 5.2.17 on 2026-09-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0006_lot_type_bordereau_projet_conducteur_travaux_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectationprojet',
            name='role_projet',
            field=models.CharField(choices=[('CP', 'Chef de Projet'), ('CT', 'Conducteur de Travaux'), ('CC', 'Chef de Chantier'), ('MOA', "Maître d'Ouvrage (Client)"), ('MOE', "Maître d'Œuvre"), ('VI', 'Consultant lecture')], default='CP', max_length=5, verbose_name='rôle sur le projet'),
        ),
        migrations.AlterField(
            model_name='projetrolemoduleoverride',
            name='module',
            field=models.CharField(choices=[('projets', 'Gestion des Projets'), ('chantier', 'Suivi Technique / Chantier'), ('ged', 'Gestion Documentaire (GED)'), ('pilotage', 'Tableaux de bord & Pilotage'), ('tiers', 'Parties Prenantes / Tiers')], max_length=30, verbose_name='module'),
        ),
    ]
