# Generated by Django 5.2.17 on 2026-09-29 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0007_alter_affectationprojet_role_projet_and_more'),
        ('tiers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='maitre_ouvrage',
            field=models.CharField(blank=True, max_length=200, verbose_name="maître d'ouvrage"),
        ),
        migrations.AlterField(
            model_name='projet',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='projets', to='tiers.tiers', verbose_name="client / maître d'ouvrage"),
        ),
    ]
