# Generated by Django 5.2.17 on 2026-10-01 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projets", "0008_projet_maitre_ouvrage_alter_projet_client"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="projet",
            name="chef_projet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="projets_geres",
                to=settings.AUTH_USER_MODEL,
                verbose_name="chef de projet",
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="date_debut_prevue",
            field=models.DateField(blank=True, null=True, verbose_name="date de début prévue"),
        ),
        migrations.AlterField(
            model_name="projet",
            name="date_fin_prevue",
            field=models.DateField(blank=True, null=True, verbose_name="date de fin prévue"),
        ),
    ]
