# Generated by Django 5.2.17 on 2026-09-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_rolemodulepermission_niveau_permission_and_more'),
        ('projets', '0008_projetrolemoduleoverride_module_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetrolemoduleoverride',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='overrides_projets', to='accounts.permission', verbose_name='permissions accordées sur ce projet'),
        ),
        migrations.AlterField(
            model_name='projetrolemoduleoverride',
            name='niveau',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Aucun'), (1, 'Lecture'), (2, 'Écriture / Saisie'), (3, 'Validation / Approbation')], null=True, verbose_name="niveau d'accès sur ce projet"),
        ),
    ]
