# Generated by Django 5.2.17 on 2026-09-30 17:49

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0009_projetrolemoduleoverride_permissions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='date_debut_baseline',
            field=models.DateField(blank=True, help_text='Date de début contractuelle initiale (figée, intacte).', null=True, verbose_name='date de début baseline v0'),
        ),
        migrations.AddField(
            model_name='lot',
            name='date_fin_baseline',
            field=models.DateField(blank=True, help_text='Date de fin contractuelle initiale (figée, intacte).', null=True, verbose_name='date de fin baseline v0'),
        ),
        migrations.AddField(
            model_name='projet',
            name='date_debut_baseline',
            field=models.DateField(blank=True, help_text='Date de début contractuelle initiale (figée, intacte).', null=True, verbose_name='date de début baseline v0'),
        ),
        migrations.AddField(
            model_name='projet',
            name='date_fin_baseline',
            field=models.DateField(blank=True, help_text='Date de fin contractuelle initiale (figée, intacte).', null=True, verbose_name='date de fin baseline v0'),
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('libelle', models.CharField(max_length=200, verbose_name='libellé')),
                ('unite', models.CharField(choices=[('M2', 'm²'), ('ML', 'ml'), ('M3', 'm³'), ('KG', 'kg'), ('U', 'u'), ('FORFAIT', 'forfait')], default='U', max_length=10, verbose_name='unité de mesure')),
                ('quantite_prevue', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='quantité prévue')),
                ('quantite_realisee', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='quantité réalisée')),
                ('avancement', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='avancement (%)')),
                ('poids', models.DecimalField(blank=True, decimal_places=3, help_text="Pondération dans l'avancement du lot ; par défaut la quantité.", max_digits=8, null=True, verbose_name='poids / pondération')),
                ('date_debut_prevue', models.DateField(verbose_name='date de début prévue')),
                ('date_fin_prevue', models.DateField(verbose_name='date de fin prévue')),
                ('date_debut_baseline', models.DateField(blank=True, help_text='Date de début contractuelle initiale (figée, intacte).', null=True, verbose_name='date de début baseline v0')),
                ('date_fin_baseline', models.DateField(blank=True, help_text='Date de fin contractuelle initiale (figée, intacte).', null=True, verbose_name='date de fin baseline v0')),
                ('ordre', models.IntegerField(default=1, verbose_name='ordre')),
                ('est_actif', models.BooleanField(default=True, verbose_name='est actif')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='projets.lot', verbose_name='lot')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'activité',
                'verbose_name_plural': 'activités',
                'db_table': 'activite',
                'ordering': ['lot', 'ordre', 'cree_le'],
            },
        ),
        migrations.CreateModel(
            name='MotifReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('code', models.CharField(help_text='Code unique du motif (ex: INTEMPERIES, CLIENT, etc.).', max_length=50, verbose_name='code')),
                ('libelle', models.CharField(help_text='Nom lisible affiché aux utilisateurs.', max_length=150, verbose_name='libellé')),
                ('description', models.TextField(blank=True, default='', help_text="Explications ou conditions d'application de ce motif.", verbose_name='description')),
                ('est_actif', models.BooleanField(default=True, help_text="Désactiver pour masquer dans les formulaires sans briser l'historique.", verbose_name='est actif')),
                ('ordre', models.PositiveIntegerField(default=1, verbose_name="ordre d'affichage")),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'motif de report',
                'verbose_name_plural': 'motifs de report',
                'db_table': 'motif_report',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('type_objet', models.CharField(choices=[('PROJET', 'Projet'), ('LOT', 'Lot'), ('ACTIVITE', 'Activité')], max_length=20, verbose_name="type d'objet")),
                ('champ', models.CharField(help_text='Nom du champ de date modifié (ex: date_fin_prevue).', max_length=50, verbose_name='champ modifié')),
                ('valeur_avant', models.DateField(verbose_name='valeur avant')),
                ('valeur_apres', models.DateField(verbose_name='valeur après')),
                ('justification', models.TextField(help_text="Justification textuelle d'au moins 30 caractères (RG-11).", verbose_name='justification')),
                ('activite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique_dates', to='projets.activite', verbose_name='activité')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='modifications_dates', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique_dates', to='projets.lot', verbose_name='lot')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique_dates', to='projets.projet', verbose_name='projet')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('motif', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='historique_dates', to='projets.motifreport', verbose_name='motif de report')),
            ],
            options={
                'verbose_name': 'historique de date',
                'verbose_name_plural': 'historiques de dates',
                'db_table': 'historique_date',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddConstraint(
            model_name='activite',
            constraint=models.CheckConstraint(condition=models.Q(('date_fin_prevue__gte', models.F('date_debut_prevue'))), name='chk_activite_dates_coherentes'),
        ),
        migrations.AddConstraint(
            model_name='activite',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('unite', 'FORFAIT'), _negated=True), ('quantite_prevue', Decimal('1.000')), _connector='OR'), name='chk_activite_forfait'),
        ),
        migrations.AddConstraint(
            model_name='motifreport',
            constraint=models.UniqueConstraint(condition=models.Q(('supprime_le__isnull', True)), fields=('code',), name='uq_motif_report_code_actif'),
        ),
        migrations.AddConstraint(
            model_name='historiquedate',
            constraint=models.CheckConstraint(condition=models.Q(('justification__regex', '^[\\s\\S]{30,}$')), name='chk_historique_date_justification_min_30'),
        ),
    ]
