# Generated by Django 5.2.17 on 2026-10-01 05:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0011_seed_motifs_et_baseline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquedate',
            name='ecart_jours',
            field=models.IntegerField(default=0, help_text="Différence en jours entre la nouvelle date et l'ancienne (valeur_après - valeur_avant).", verbose_name='écart en jours'),
        ),
        migrations.AddIndex(
            model_name='historiquedate',
            index=models.Index(fields=['type_objet', 'champ'], name='hist_date_type_champ_idx'),
        ),
        migrations.AddIndex(
            model_name='historiquedate',
            index=models.Index(fields=['projet', '-cree_le'], name='hist_date_projet_idx'),
        ),
        migrations.AddIndex(
            model_name='historiquedate',
            index=models.Index(fields=['auteur', '-cree_le'], name='hist_date_auteur_idx'),
        ),
        migrations.AddIndex(
            model_name='historiquedate',
            index=models.Index(fields=['ecart_jours'], name='hist_date_ecart_idx'),
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION verifier_immuabilite_historique_date()
            RETURNS TRIGGER AS $$
            BEGIN
                RAISE EXCEPTION 'RG-07 : La table historique_date est strictement immuable (append-only). Opération % interdite.', TG_OP;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS trg_historique_date_immuable ON historique_date;
            CREATE TRIGGER trg_historique_date_immuable
            BEFORE UPDATE OR DELETE ON historique_date
            FOR EACH ROW
            EXECUTE FUNCTION verifier_immuabilite_historique_date();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_historique_date_immuable ON historique_date;
            DROP FUNCTION IF EXISTS verifier_immuabilite_historique_date();
            """,
        ),
    ]

