# Generated by Django 5.2.17 on 2026-10-01 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0012_add_ecart_jours_and_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='chef_projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_geres', to=settings.AUTH_USER_MODEL, verbose_name='chef de projet'),
        ),
    ]
