# Generated by Django 5.2.17 on 2026-10-01 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0009_identification_projet'),
        ('projets', '0013_alter_projet_chef_projet'),
    ]

    operations = [
    ]
