# Generated by Django 5.2.17 on 2026-10-02 09:39

import apps.projets.models.contrat
import apps.projets.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projets", "0015_harmonisation_creation_projet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjetContrat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                ("modifie_le", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "supprime_le",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Non nul = ligne supprimée logiquement. Jamais de suppression physique.",
                        null=True,
                        verbose_name="supprimé le",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        max_length=255,
                        storage=apps.projets.storage.StockageContrats(),
                        upload_to=apps.projets.models.contrat.chemin_contrat,
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("taille", models.PositiveBigIntegerField()),
                ("type_contenu", models.CharField(max_length=50)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nul lorsque l'écriture vient du système.",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrats",
                        to="projets.projet",
                    ),
                ),
                (
                    "supprime_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="supprimé par",
                    ),
                ),
            ],
            options={
                "db_table": "projet_contrat",
                "ordering": ["cree_le", "id"],
            },
        ),
    ]
