# Generated by Django 5.2.17 on 2026-10-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0016_projetcontrat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('EN_RETARD', 'En retard'), ('CRITIQUE', 'Critique'), ('SUSPENDU', 'Suspendu'), ('TERMINE', 'Terminé'), ('BLOQUE', 'Bloqué'), ('DESACTIVE', 'Désactivé'), ('RESILIE', 'Résilié'), ('ARCHIVE', 'Archivé')], default='EN_ATTENTE', max_length=20, verbose_name='statut'),
        ),
    ]
