# Generated by Django 5.2.17 on 2026-10-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0017_alter_projet_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='statut',
            field=models.CharField(choices=[('PLANIFIE', 'Planifiée'), ('EN_COURS', 'En cours'), ('EN_RETARD', 'En retard'), ('SUSPENDU', 'Suspendu'), ('CLOTURE', 'Clôturée')], db_index=True, default='PLANIFIE', max_length=20, verbose_name='statut'),
        ),
        migrations.AddField(
            model_name='lot',
            name='statut',
            field=models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('EN_RETARD', 'En retard'), ('SUSPENDU', 'Suspendu'), ('CLOTURE', 'Clôturé')], db_index=True, default='PLANIFIE', max_length=20, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('EN_RETARD', 'En retard'), ('CRITIQUE', 'Critique'), ('SUSPENDU', 'Suspendu'), ('RECEPTIONNE', 'Réceptionné'), ('TERMINE', 'Terminé'), ('BLOQUE', 'Bloqué'), ('DESACTIVE', 'Désactivé'), ('RESILIE', 'Résilié'), ('ARCHIVE', 'Archivé')], default='EN_ATTENTE', max_length=20, verbose_name='statut'),
        ),
    ]
