# Generated by Django 5.2.17 on 2026-10-02 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_rolemodulepermission_module_catalogue_and_more'),
        ('catalogue', '0002_peupler_catalogue_depuis_public'),
        ('projets', '0021_equipechantier_membreequipechantier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projetrolemoduleoverride',
            name='module_catalogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overrides_projets_catalogue', to='catalogue.cataloguemodule', verbose_name='module catalogue'),
        ),
        migrations.AddField(
            model_name='projetrolemoduleoverride',
            name='permissions_catalogue',
            field=models.ManyToManyField(blank=True, db_table='projet_role_module_override_permissions_catalogue', related_name='overrides_projets_catalogue', to='catalogue.cataloguepermission', verbose_name='permissions catalogue accordées sur ce projet'),
        ),
        migrations.AddConstraint(
            model_name='projetrolemoduleoverride',
            constraint=models.UniqueConstraint(condition=models.Q(('module_catalogue__isnull', False), ('supprime_le__isnull', True)), fields=('projet', 'role', 'module_catalogue'), name='uq_projet_role_module_catalogue_actif'),
        ),
    ]
