# Generated by Django 5.2.17 on 2026-10-05 10:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0025_motif_lots_activites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='badge_sante',
            field=models.CharField(blank=True, choices=[('VERT', 'Vert'), ('ORANGE', 'Orange'), ('ROUGE', 'Rouge')], help_text='Badge final (après application du plancher de gravité).', max_length=10, null=True, verbose_name='badge de santé'),
        ),
        migrations.CreateModel(
            name='ArretChantier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('date_debut', models.DateField(verbose_name='date de début')),
                ('date_fin', models.DateField(blank=True, help_text="Date de reprise effective ; nulle tant que l'arrêt est en cours.", null=True, verbose_name='date de fin')),
                ('motif', models.TextField(verbose_name="motif de l'arrêt")),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('declare_par', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='arrets_declares', to=settings.AUTH_USER_MODEL, verbose_name='déclaré par')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrets_chantier', to='projets.projet', verbose_name='projet')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'arrêt de chantier',
                'verbose_name_plural': 'arrêts de chantier',
                'db_table': 'arret_chantier',
                'ordering': ['-date_debut'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('date_fin__isnull', True)), fields=('projet',), name='uq_arret_ouvert_par_projet'), models.CheckConstraint(condition=models.Q(('date_fin__isnull', True), ('date_fin__gte', models.F('date_debut')), _connector='OR'), name='chk_arret_date_fin_gte_debut')],
            },
        ),
        migrations.CreateModel(
            name='SanteProjetSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supprime_le', models.DateTimeField(blank=True, db_index=True, help_text='Non nul = ligne supprimée logiquement. Jamais de suppression physique.', null=True, verbose_name='supprimé le')),
                ('date_calcul', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='date de calcul')),
                ('declencheur_type', models.CharField(blank=True, default='', help_text='Origine du recalcul (ex: RAPPORT, BLOCAGE, ARRET, REPROGRAMMATION, JOB_QUOTIDIEN).', max_length=50, verbose_name='type de déclencheur')),
                ('declencheur_id', models.CharField(blank=True, default='', max_length=100, verbose_name='identifiant du déclencheur')),
                ('score', models.PositiveSmallIntegerField(help_text='Score global de 0 à 100.', verbose_name='score de santé')),
                ('badge_brut', models.CharField(choices=[('VERT', 'Vert'), ('ORANGE', 'Orange'), ('ROUGE', 'Rouge')], max_length=10, verbose_name='badge brut')),
                ('badge_final', models.CharField(choices=[('VERT', 'Vert'), ('ORANGE', 'Orange'), ('ROUGE', 'Rouge')], help_text='Badge après application éventuelle du plancher de gravité.', max_length=10, verbose_name='badge final')),
                ('plancher_applique', models.BooleanField(default=False, verbose_name='plancher de gravité appliqué')),
                ('p_delais', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='pénalité délais (0-40)')),
                ('p_retard', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='sous-pénalité retard')),
                ('p_malus', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='sous-pénalité malus reports')),
                ('p_blocages', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='pénalité blocages (0-40)')),
                ('p_reporting', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='pénalité reporting (0-20)')),
                ('avancement_physique', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='avancement physique (%)')),
                ('avancement_temporel', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='avancement temporel (%)')),
                ('delta', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='retard en points (temporel - physique)')),
                ('mode_ponderation', models.CharField(default='UNIFORME', max_length=20, verbose_name='mode de pondération')),
                ('nb_reports', models.PositiveIntegerField(default=0, verbose_name='nombre de reports accordés')),
                ('blocages_ouverts_par_severite', models.JSONField(default=dict, verbose_name='blocages ouverts par sévérité')),
                ('taux_reporting', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='taux de reporting')),
                ('jours_attendus', models.PositiveSmallIntegerField(default=0, verbose_name='jours attendus')),
                ('jours_couverts', models.PositiveSmallIntegerField(default=0, verbose_name='jours couverts')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Nul lorsque l'écriture vient du système.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots_sante', to='projets.projet', verbose_name='projet')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'snapshot de santé projet',
                'verbose_name_plural': 'snapshots de santé projet',
                'db_table': 'sante_projet_snapshot',
                'ordering': ['-date_calcul'],
                'indexes': [models.Index(fields=['projet', '-date_calcul'], name='idx_sante_snap_proj_date')],
            },
        ),
    ]
