# Generated by Django 5.2.17 on 2026-10-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0026_projet_badge_sante_arretchantier_santeprojetsnapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affectationprojet',
            name='role',
        ),
        migrations.DeleteModel(
            name='ProjetRoleModuleOverride',
        ),
    ]
