# Generated by Django 5.2.17 on 2026-10-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0027_supprimer_override_et_role_affectation'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='sans_chef_projet',
            field=models.BooleanField(default=False, verbose_name='sans chef de projet'),
        ),
        migrations.AlterField(
            model_name='affectationprojet',
            name='role_projet',
            field=models.CharField(blank=True, choices=[('CP', 'Chef de Projet'), ('CT', 'Conducteur de Travaux'), ('CC', 'Chef de Chantier'), ('MOA', "Maître d'Ouvrage (Client)"), ('MOE', "Maître d'Œuvre"), ('VI', 'Consultant lecture')], default='CP', max_length=5, verbose_name='rôle sur le projet'),
        ),
    ]
