# Generated by Django 5.2.17 on 2026-10-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0027_activite_colaborateur'),
        ('projets', '0028_projet_sans_chef_projet_and_more'),
    ]

    operations = [
    ]
